#!/bin/bash
set -euxo pipefail

cd "QM Course Materials/Problems+exercises"

if git diff-index --name-only --cached --diff-filter=d HEAD | grep --quiet '.*\.adoc$'; then
	asciidoctor ./*.adoc
	git add ./*.html
fi
