[.qm-chapter.chap-2]
= Chapter 2: Time-Independent {sch} Equation
include::shared_attributes.adoc[]

== Stationary States

* {q-num} Which of the following are always true when we use separation of variables to solve the Schrodinger equation?
.. ++\(\Psi(x,t)=\psi(x)\phi(t)\)++
.. Both sides of the Schrodinger equation are constant
.. ++\(\Psi(x,t)\)++ is a stationary state
.. ++\(V(x,t) = V(x)\)++
.. ++\(i\hbar \frac{\partial \Psi}{\partial t} = 0\)++

+
.Solution
[%collapsible]
====
Only (a) is true. NEED TO EDIT! Check other answers in 2
====

* {q-num} Why is ++\(\Psi_E(x,t)= \psi_E(x)e^{-iEt/\hbar}\)++ called a stationary state if it is time-dependent?
+
[{sublist-style}]
. Show that ++\(|\Psi_E(x,t)|^2 = |\psi_E(x)|^2\)++.
. Show that ++\( \Braket{p} = 0\)++ for ++\(\Psi_E(x,t)\)++.

+
.Solution
[%collapsible]
====
[{sublist-style}]
. {nbsp}
++\[\begin{align*}|
\Psi_E(x,t)|^2 &= \Psi_E^* \Psi_E\\
&= (\psi_E^*(x)e^{iEt/\hbar}) (\psi_E(x) e^{-iEt/\hbar}) \\
&= |\psi_E(x)|^2
\end{align*}\]++
. For a particle in state ++\(\Psi_E\)++,
++\[\begin{align*}
\Braket{x}&=\int_{\mathcal D} x|\Psi_E(x,t)|^2 \,dx\\
&=\int_{\mathcal D} x|\psi_E(x)|^2\,dx\\
&=\textrm{constant w.r.t time}
\end{align*}\]++
So ++\(\frac{d\Braket{x}}{dt}=0\)++.
Then, Ehrenfest's theorem says that ++\(\Braket{p}=m\frac{d\Braket{x}}{dt}=0\)++.

====


* {q-num} [Similar to Griffiths text (not a problem). Need to modify more]
The classical Hamiltonian, the total energy in a system, is given by ++\(H(x,p)=\frac{p^2}{2m}+V(x)\)++, where ++\(\frac{p^2}{2m}\)++ is the kinetic energy and ++\(V(x)\)++ is the potential energy.
+
[{sublist-style}]
** Using the quantum mechanical substitution rule ++\(p \rightarrow -i\hbar \frac{\partial}{\partial x}\)++, find the quantum mechanical Hamiltonian ++\(\hat H\)++.
Substituting this Hamiltonian into the time-independent {sch} equation
++\[-\frac{\hbar^2}{2m}\frac{d^2\psi}{dx^2}+V\psi = E\psi\]++
yields ++\(\hat H\psi=E\psi\)++.
** Show that ++\(\braket{\hat H} = E\)++.
** Show that ++\(\braket{\hat H^2} = E^2\)++. (Hint: first show that ++\(\hat H^2\psi=E^2\psi\)++)
** Conclude that the variance of ++\(\hat H\)++ is 0.

+
In other words, every measurement of the total energy of a solution to the time-dependent {sch} equation will yield ++\(E\)++.



* {q-num} If you were to measure the energy of a particle with the wavefunction ++\(\Psi(x,t) = \frac{4}{5}\Psi_1(x,t) - \frac{3i}{5} \Psi_2(x,t)\)++, what is the probability that you’d measure the energy to be ++\(E_2\)++?
+
.Solution
[%collapsible]
====
When a wavefunction is written as ++\(\Psi(x,t)=\sum_n c_n\Psi_n(x)=\sum_n c_n\psi_n(x) e^{-iE_n t/\hbar}\)++, the probability that a measurement of the energy yields ++\(E_n\)++ is ++\(|c_n|^2\)++.
The probability that energy is ++\(E_2\)++, then, is ++\(\left|c_2\right|^2=\left|-\frac{3i}{5}\right|^2=\frac{9}{25}\)++.
(As there are only two eigenstates in this example, the probability of measuring an energy of ++\(E_1\)++ must be one minus this, or ++\(\frac{16}{25}\)++.)
====

* {q-num} Griffiths's questions 2.1 and 2.2 are very good. Check to see how those can be modified.


== The Infinite Square Well
=== Questions

* {q-num} The solutions to the time-independent {sch} equation in the infinite square well of width \(a\) are ++\(\psi_n(x)=\sqrt{2/a}\sin\left(\frac{n\pi}{a}x\right)\)++ with ++\(n\ge 1\)++.
Show that these functions are _orthonormal_, i.e., that ++\(\Braket{\psi_m,\psi_n}\)++ is 1 when ++\(m=n\)++ and 0 otherwise.
(Hint: ++\(\cos\)++ is an even function, ++\(\sin\)++ is an odd function, and ++\(\cos(a+b)=\cos a\cos b-\sin a\sin b\)++.)
+
.Solution
[%collapsible]
====
Using the trigonometric identities in the hint, we have
++\[\begin{align*}
\cos(a+b)&=\cos a\cos b-\sin a\sin b\\
\cos(a-b)&=\cos a\cos b+\sin a\sin b\\
\cos(a+b)-\cos(a-b)&=-2\sin a\sin b\\
\sin a \sin b &=\frac{1}{2}(\cos(a-b) - \cos(a+b))
\end{align*}\]++
Regardless of whether ++\(m=n\)++,
++\[\begin{align*}
\Braket{\psi_m,\psi_n}&= \int_0^a \psi_m^*\psi_n\,dx\\
&=\int_0^a \sqrt\frac{2}{a}\sin\left(\frac{m\pi}{a}x\right)\ \sqrt\frac{2}{a}\sin\left(\frac{n\pi}{a}x\right)\,dx\\
&=\frac{1}{a}\int_0^a \cos\left(\frac{(m-n)\pi}{a}x\right)-\cos\left(\frac{(m+n)\pi}{a}x\right)\,dx
\end{align*}\]++
And for ++\(k\ne 0\)++,
++\[\begin{align*}
\int_0^a \cos\left(\frac{k\pi}{a}x\right)\,dx=\left.\frac{a}{k\pi}\sin\left(\frac{k\pi}{a}x\right)\right|^a_0=0
\end{align*}\]++
When ++\(m=n\)++, ++\(\Braket{\psi_m,\psi_n}\)++ becomes
++\[\begin{align*}
\frac{1}{a}\int_0^a \cos 0-\cos\left(\frac{(m+n)\pi}{a}x\right)\,dx=\frac{1}{a}\int_0^a dx=1
\end{align*}\]++
When ++\(m\ne n\)++, both of the ++\(\cos\)++ terms in the integral are of the form ++\(\cos\left(\frac{k\pi}{a}x\right),k\ne 0\)++ and so they both integrate to 0, and then ++\(\Braket{\psi_m,\psi_n}=0\)++.
====

* {q-num} Let ++\(V\)++ be the potential in the infinite square well:
\[V(x) = \begin{cases}
            0 &  0 \leq x \leq a \\
            \infty &  \textrm{otherwise}
\end{cases}
\]
+
[{sublist-style}]
.. Find the general solution using the time-independent {sch} equation, the simple harmonic oscillator equation, and applying the constraints of the infinite square well.
.. Apply the boundary conditions to solve for the constants ++\(A\)++ and ++\(B\)++.
.. Find solutions for ++\(kx\)++ and, using those results, solve for the possible values of the energy ++\(E\)++.
.. How does this result compare to what we’d expect from a classical case?
.. Use this result and normalize ++\(\Psi\)++ to solve for stationary states.
.. What is the significance of this result?

+
.Solution
[%collapsible]
====
[{sublist-style}]
. Inside the well, ++\(V(x) = 0\)++, and so the {sch} equation says ++\(\frac{-\hbar^2}{2m}\frac{\partial^2\psi}{\partial x^2}=E\psi(x)\)++.
Letting ++\(k=\sqrt{2mE/\hbar}\)++, we have
++\(\frac{d^2\psi(x)}{dx^2}= -k^2\psi(x)\)++.
 Assuming ++\(E\geq0\)++, the
solution isn’t contradicting the boundary conditions. Recognize:
++\(\frac{d^2\psi(x)}{dx^2} + k^2\psi = 0\)++ as the equation of the
simple harmonic oscillator.
The solution of this equation is
++\(\psi(x)=A\sin(kx)+B\cos(kx)\)++ where ++\(A,B\)++ are constants determined by the boundary conditions.

. For ++\(\psi\)++ to be continuous at ++\(0\)++ and ++\(a\)++, we must have ++\(\psi(0) =\psi(a)=0\)++.
So ++\(\psi(0) = A\sin(0) + B\cos(0) = B\)++, and hence
++\(B=0\)++.
This leaves us with: ++\(\psi(x)=A\sin(kx)\)++,
so either ++\(A=0\)++ — in which case ++\(\psi\)++ is 0 everywhere, which is not a valid wavefunction — or ++\(\sin(ka)=0\)++.
. The boundary condition ++\(\psi(a)=A\sin(ka)=0\)++ requires that ++\(k= \frac{n\pi}{a}\)++ with ++\(n\)++ an integer.
But if ++\(n=0\)++ then ++\(\psi(x)=0\)++ everywhere, so ++\(n\)++ must in fact be nonzero.
Additionally, ++\(\sin\left(\frac{-n\pi}{a}x\right)=-\sin\left(\frac{n\pi}{a}x\right)\)++ — a solution we've already accounted for, since ++\(A\)++ can absorb the leading minus sign — so the distinct solutions are ++\(k= \frac{n\pi}{a}\)++ for positive integer ++\(n\)++.
Therefore the permissible values of the energy ++\(E\)++ are
++\(E_n=\frac{\hbar^2 k_n^2}{2m} =\frac{\pi^2 n^2\hbar^2}{2ma^2}\)++ with ++\(n\)++ a positive integer.

. Unlike the classical case, a quantum particle in the infinite square well cannot have an arbitrary value of energy.
Instead, a quantum particle can only be in a superposition of one of these special _allowed_ states that fit within the constraints of the infinite square well.
When observed, a quantum particle in the infinite square well will have an energy that is one of the ++\(E_n\)++.
. To compute the integral, we'll need the fact that ++\(\sin^2(a)=\frac{1}{2}(1-\cos(2a))\)++.
++\[\begin{align*}
|\psi_n(x)|^2&=\int_0^a |A|^2\sin^2\left(\frac{n\pi}{a}x\right)\,dx\\
&=|A|^2\int_0^a\frac{1}{2}\left[1-\cos\left(\frac{2n\pi}{a}x\right)\right]\,dx\\
&=\frac{|A|^2}{2}\left.\left[x-\frac{\sin(\frac{2n\pi}{a}x)}{\frac{2n\pi}{a}}\right]\right|^a_0\\
&=\frac{|A|^2a}{2}
\end{align*}\]++
For the norm to be 1, we must have ++\(|A|=\sqrt{\frac{2}{a}}\)++.
Any choice of ++\(A\)++ satisfying this will do — ++\(A\)++ can be complex, but its phase doesn't matter — so let's pick the most obvious and simplest choice, ++\(A=\sqrt{\frac{2}{a}}\)++, to obtain ++\(\psi_n(x)=\sqrt\frac{2}{a}\sin\left(\frac{\pi}{a}x\right)\)++.
(In general, it's always simplest to choose the stationary states that are real-valued.)

====

* {q-num} What are the four properties of the functions
++\(\Psi_n(x)\)++?
Are these properties unique to the infinite square well?
Why are they so important?
+
.Solution
[%collapsible]
====
. These functions are alternatively even and odd about
the center of the potential well.
This is true for any symmetrical potential well.
. With increasing ++\(n\)++, each successive state has one more node in the wavefunction.
This is true regardless of the shape of the potential well.
. They are mutually orthogonal: ++\(\int \psi_m(x)^*\psi_n(x)\,dx=\delta_{mn}\)++. This is true regardless of the potential well, as
long as it's normalized.
. The state functions form a complete set. This is not
universal, but is almost always applicable for any potential we will
encounter.

These properties are so important because they hold true for almost all potentials, which means we can apply these four properties to help solve many different types of problems.
====

* {q-num} A particle in the infinite square well of width ++\(a\)++ has the following initial wave function: ++\(\Psi(x,0)=A(\psi_1(x) + \psi_4(x))\)++.
+
[{sublist-style}]
.. Normalize to find ++\(A\)++.
(You can assume ++\(A\)++ is real.)
.. Find the constants ++\(c_n\)++ in the expression ++\(\Psi(x,0)=\sum_n c_n\psi_n(x)\)++.
.. Compute ++\(\left|\Psi(x,t)\right|^2\)++ (this isn't very useful on its own, but you'll need it for part (d)).
.. Compute {expect-x} as a function of ++\(t\)++.
What is the frequency of oscillations?
What is the amplitude?

+
.Solution
[%collapsible%open]
====
[{sublist-style}]
. To normalize, we set ++\(\left\|\Psi\right\|^2=\int_0^a\left|\Psi(x,0)\right|^2\,dx=1\)++ and simply compute, using the fact that the ++\(\psi_n\)++ are orthonormal over ++\([0,a]\)++.
(In the integrals below, for brevity, we omit the ++\(x\)++ as an argument of the [.no-break]#++\(\psi_n\)++.#)
++\[\begin{align*}
1&=\int_0^a\left|\Psi(x,0)\right|\\
&=\int_0^a\left|A(\psi_1+\psi_4)\right|^2\,dx\\
&=\int_0^a\left|A\right|^2(\psi_1^2+2\psi_1\psi_4+\psi_4^2)\,dx\\
&=\left|A\right|^2(1+2\cdot 0+1)\\
&=2\left|A\right|^2
\end{align*}\]++
So ++\(A=\frac{1}{\sqrt{2}}\)++ (or any complex number with that magnitude, but we can always take the normalization constant to be real, so we might as well do so.)
. Simply referring to the expression for ++\(\Psi\)++ in the problem statement, we have
++\[\Psi(x,0)=A(\psi_1(x)+\psi_4(x))=\frac{1}{\sqrt{2}}\psi_1(x)+\frac{1}{\sqrt{2}}\psi_4(x)\]++
so ++\(c_1=c_4=\frac{1}{\sqrt{2}}\)++ and the other ++\(c_n\)++ are zero.
. In general, if ++\(\Psi(x,0)=\sum_n c_n\psi_n(x)\)++, then ++\(\Psi(x,t)=\sum_n c_n\psi_n(x)\varphi_n(t) \)++ where [.no-break]#++\(\varphi_n(t):=e^{-iE_nt/\hbar}\)++#.
And if we write [.no-break]#++\(E_n=\frac{n^2\pi^2\hbar^2}{2ma^2}=n^2E_1\)++,# then [.no-break]#++\(\varphi_n(t)=e^{-i n^2E_1t/\hbar}\)++,# and so we can compute something that we'll need very soon:
++\[\begin{align*}
\varphi_1(t)\varphi_4^* (t) &= e^{-i E_1t/\hbar}\left(e^{-16i E_1t/\hbar}\right)^* =e^{15iE_1t/\hbar}
\end{align*}\]++
which means
++\[\begin{align*}
\varphi_1(t)\varphi_4^* (t) + \varphi_1^*(t)\varphi_4(t)&=\varphi_1(t)\varphi_4^* (t) + (\varphi_1(t)\varphi_4^*(t))^*\\
&=2\Re[\varphi_1(t)\varphi_4^*(t)]\\
&=2\cos(15E_1t/\hbar)
\end{align*}\]++
+
Now to compute ++\(\left|\Psi(x,t)\right|^2\)++.
Below, for brevity, we'll write ++\(\varphi_n\)++ instead of ++\(\varphi_n(t)\)++ and ++\(\psi_n\)++ instead of ++\(\psi_n(x)\)++, and use the fact that ++\(c_n\)++ and ++\(\psi_n\)++ are real.
++\[\begin{align*}
\left|\Psi(x,t)\right|^2&=\Psi(x,t)^*\Psi(x,t)\\
&=\left(c_1\psi_1\varphi_1+c_4\psi_4\varphi_4\right)^*\left(c_1\psi_1\varphi_1+c_4\psi_4\varphi_4\right)\\
&=\left|c_1\psi_1\varphi_1\right|^2+\left|c_4\psi_4\varphi_4\right|^2\\
&\quad+((c_1\varphi_1)^* (c_4\varphi_4)+(c_1\varphi_1)(c_4\varphi_4)^*)\psi_1\psi_4\\
&=c_1^2\psi_1^2+c_4^2\psi_4^2+c_1c_4(\varphi_1^* \varphi_4+\varphi_1\varphi_4^*)\psi_1\psi_4\\
&=\frac{1}{2}\psi_1^2+\frac{1}{2}\psi_4^2+\cos(15E_1t/\hbar)\psi_1\psi_4
\end{align*}\]++
. We wish to compute ++\(\braket x\)++ (as a function of ++\(t\)++), which is just the following expression:
++\[\begin{align*}
\braket x&=\int_0^a x\left|\Psi(x,t)\right|^2\,dx
\end{align*}\]++
Before proceeding we'll want the following facts (which you can feel free to derive on your own).
If ++\(m\)++ and ++\(n\)++ are integers, then if ++\(m\ne n\)++, then
++\[\begin{align*}
\int_0^a x\sin\left(\frac{m\pi}{a}x\right)\sin\left(\frac{n\pi}{a}x\right)\,dx&=\frac{2mna^2((-1)^{m+n}-1)}{(m^2-n^2)^2\pi^2}
\end{align*}\]++
and if ++\(m=n\)++ then
++\[\begin{align*}
\int_0^a x\sin\left(\frac{m\pi}{a}x\right)\sin\left(\frac{n\pi}{a}x\right)\,dx=\int_0^a x\sin^2\left(\frac{n\pi}{a}x\right)\,dx=\frac{a^2}{4}
\end{align*}\]++
(Note that this does not actually depend on ++\(n\)++.)
So,
++\[\begin{align*}
\int_0^a x\,\psi_1^2\,dx&=\int_0^a x\left[\sqrt{2/a}\sin\left(\frac{\pi}{a} x\right)\right]^2\,dx\\
&=\frac{2}{a}\int_0^ax\sin^2\left(\frac{\pi}{a} x\right)\,dx\\
&=\frac{2}{a}\cdot\frac{a^2}{4}\\
&=\frac{a}{2}\\\\
\int_0^a x\,\psi_4^2\,dx&=\frac{a}{2}\\\\
\int_0^a x\,\psi_1\psi_4 \,dx&=\int_0^ax\left[\sqrt{2/a}\sin\left(\frac{\pi}{a}x\right)\right]\left[\sqrt{2/a}\sin\left(\frac{4\pi}{a}x\right)\right]\,dx\\
&=\frac{2}{a}\cdot\frac{2\cdot1\cdot4a^2(-2)}{(1^2-4^2)^2\pi^2}\\
&=-\frac{32a}{225\pi^2}
\end{align*}\]++
+
So, we may finally compute our answer:
++\[\begin{align*}
\braket x&=\int_0^a x\left|\Psi(x,t)\right|^2\,dx\\
&=\int_0^a x\left(\frac{1}{2}\psi_1^2+\frac{1}{2}\psi_4^2+\cos(15E_1t/\hbar)\psi_1\psi_4\right)\,dx\\
&=\frac{1}{2}\left(\frac{a}{2}\right)+\frac{1}{2}\left(\frac{a}{2}\right)+\cos(15E_1t/\hbar)\left(-\frac{32a}{225\pi^2}\right)\\
&=\frac{a}{2}-\frac{32a\cos(15E_1t/\hbar)}{225\pi^2}\\
&=a\left(\frac{1}{2}-\frac{32}{225\pi^2}\cos(15E_1t/\hbar)\right)
\end{align*}\]++
The frequency of oscillation is ++\(\frac{15E_1}{2\pi\hbar}=\frac{15\pi\hbar}{4ma^2}\)++.
The particle oscillates between ++\(a\left(\frac{1}{2}\pm\frac{32}{225\pi^2}\right)\)++ and so its amplitude is ++\(\frac{64a}{225\pi^2}\)++.
+
Notably, unlike a classical particle, its amplitude is _not_ ++\(\frac{a}{2}\)++ [.no-break]#(++\(\frac{64}{225\pi^2}\approx0.0288\ll 0.5\)++).#
The expected position of a quantum mechanical particle _cannot_ get arbitrarily close to the walls of the well — why not?

====


== The Harmonic Oscillator

=== Questions

* {q-num} Show that every solution of the time-independent harmonic oscillator {sch} equation ++\(\hat H\psi = E\psi\)++ lies on the same "`ladder`": for every pair of solutions ++\(\psi_a,\psi_b\)++ with ++\(a >b\)++, there is some ++\(m\)++ for which ++\(\psi_a=k\hat a_{+}^m\psi_b\)++ (for some normalization constant ++\(k\)++).
+
.Solution
[%collapsible%open]
====
Suppose ++\(\psi_a\)++ lies on ladder ++\(A\)++ and ++\(\psi_b\)++ on ladder ++\(B\)++.
By successively applying the lowering operator to ++\(\psi_a\)++ and ++\(\psi_b\)++, we obtain the bottommost rungs on the two ladders, which we'll denote ++\(\psi_{A,0}\)++ and ++\(\psi_{B,0}\)++.
By virtue of being the bottommost rungs, they must satisfy ++\(\hat a_-\psi_{A,0}=\hat a_-\psi_{B,0}=0\)++.
Substituting ++\(\hat a_-=\frac{1}{\sqrt{2\hbar m\omega}}(i\hat p+m\omega x)\)++, we obtain the differential equation ++\(\frac{d\psi_{L,0}}{dx}=-\frac{m\omega}{\hbar}x\psi_{L,0}\)++ for ++\(L=A,B\)++.
In both cases this leads to the same solution:
++\[
\psi_{A,0}(x)=\psi_{B,0}(x)=\left(\frac{m\omega}{\pi\hbar}\right)^{\frac{1}{4}}e^{-\frac{m\omega}{2\hbar}x^2}
\]++
So the ladders share their bottom rung, which we may now write as just ++\(\psi_0(x)\)++.
Every subsequent rung — on either ladder — is given by successive applications of the raising operator: ++\(\psi_{A,n}=\psi_{B,n}=k(\hat a_+)^n\psi_{0}\)++.
So,
++\[\begin{align*}
\psi_a&=k(\hat a_+)^{a}\psi_0\\
&=k(\hat a_+)^{a-b}(\hat a_+)^b\psi_0\\
&=k(\hat a_+)^{n-b}\psi_b
\end{align*}\]++
as desired.
====

* {q-num} For small displacements, the harmonic oscillator is a good second-order approximation of many potential fields.
What is an example of a potential field ++\(V(x)\)++ for which the harmonic oscillator is _not_ a good approximation?
+
.Solution
[%collapsible]
====
++\(V(x)=x^4\)++ is one such potential, as it has no quadratic terms.
====

* {q-num} *Coherent States* A _coherent state_ of the harmonic oscillator is a "`minimum uncertainty wavepacket`": a Gaussian wavefunction ++\(\Psi\)++ for which ++\(\sigma_x^2+\sigma_p^2\)++ at ++\(t=0\)++ is minimized.
.. Find ++\(\sigma_x\)++ and ++\(\sigma_p\)++ at ++\(t=0\)++.
.. Show that ++\(\sigma_x\)++ and ++\(\sigma_p\)++ are, in fact, constant over time (hence the name _coherent_ state — the probability distribution does not change shape over time).
.. Show that ++\(\Psi\)++ is an eigenfunction of the lowering operator ++\(\hat a_-\)++ (or the raising operator, as they have the same eigenvectors).

* {q-num} [Thaller] Show that solutions ++\(\Psi(x,t)\)++ of the harmonic oscillator satisfy ++\(\Psi(x,t+\pi)=e^{-i\pi/2}\Psi(-x,t)\)++.
(Corollary: ++\(\Psi(x,t+2\pi)=-\Psi(x,t)\)++.)
So, while the probability distribution has period ++\(2\pi\)++, matching the situation in classical physics, the wavefunction itself only has period ++\(4\pi\)++.

* {q-num} Show that in the harmonic oscillator, ++\( \frac{d\braket p}{dt}=-k\braket x\)++.

* {q-num} [Adapted from Griffiths 2.16]
The *Rodrigues formula* says that ++\(H_n(x)=(-1)^n e^{x^2}\frac{d^n}{dx^n}(e^{-x^2})\)++.
+
[{sublist-style}]
** Use this to derive the recurrence relation ++\(H_{n+1}(x)=2xH_n(x)-2nH_{n-1}(x)\)++.
** Show that ++\(H_n\)++ satisfies ++\(\frac{d H_n(x)}{dx}=2nH_{n-1}(x)\)++.
** Show that ++\(H_n(x)=\left.\frac{d^n}{dz^n}(e^{-z^2+2zx})\right|_{z=0}\)++.

:!qn:
=== Demonstrations

* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/harmonic_oscillator/harmonic_oscillator_inlined.html?t=1657044816[Harmonic oscillator stationary states (static)^]
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/harmonic_oscillator/harmonic_oscillator_evolution_inlined.html?t=1657044816[Harmonic oscillator evolution over time^]

== The Free Particle

* {q-num} Show that the more localized a free particle is initially (++\(\braket{x^2}\)++ small at ++\(t=0\)++), the faster it will spread out over time (++\(\frac{d}{dt}\braket{x^2}\)++ large for small [.no-break]#++\(t\)++);# and, inversely, show that the less localized a free particle is initially, the more slowly it will spread out over time.
(Hint: this depends heavily on the dispersion relation for particles, [.no-break]#++\(\omega=\frac{\hbar k^2}{2m}\)++.)#

* {q-num} Suppose a free particle has the initial wavefunction [.no-break]#++\(\Psi(x,0)=\delta(x)\)++#, where ++\(\delta(x)\)++ is the Dirac delta "`function`".
Compute ++\(\Psi(x,t)\)++.


* {q-num} Suppose a free particle has the initial wavefunction [.no-break]#++\(\psi(x) = \frac{\sin(x)}{\pi x}\)++.#
(Take our word for it that this wavefunction is already normalized.)
[{sublist-style}]
. Find ++\(F(k):=\mathcal{F}[\psi](k)\)++.
You may use computational software to help you calculate the integral.
(But don't just type in "`Fourier transform of ++\(\frac{\sin(x)}{\pi x}\)++`"!)
. Verify that your result satisfies ++\(\Psi(x,0)=\frac{\sin(x)}{\pi x}\)++.
. If you're feeling particularly ambitious, find ++\(\Psi(x,t)\)++.
Note that the integral involves the so-called special function the _error function_, ++\(\textrm{erf}(x)\coloneqq\frac{2}{\sqrt\pi}\int_0^xe^{-t^2}\,dt\)++, which has no elementary form.

+
.Solution
[%collapsible]
====
[{sublist-style}]
. {nbsp}
++\[\begin{align*}
F(k)&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty \psi(x)e^{-ikx}\,dx\\
&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty \frac{1}{\pi} \ \frac{\sin(x)e^{-ikx}}{x}\,dx\\
&= \textrm{(... computational software ...)}\\
&=\frac{1}{\pi\sqrt{2\pi}}\begin{cases}\pi&-1<k<1\\
0&\textrm{otherwise}
\end{cases}\\
&=\begin{cases}\frac{1}{\sqrt{2\pi}}&-1<k<1\\
0&\textrm{otherwise}
\end{cases}
\end{align*}\]++

. For all ++\(t\)++,
++\[\begin{align*}
\Psi(x,t)&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty F(k)e^{i(kx-\frac{\hbar k^2}{2m}t)}\,dk\\
&=\frac{1}{\sqrt{2\pi}}\int_{-1}^1 \frac{1}{\sqrt{2\pi}}e^{i(kx-k^2\frac{\hbar t}{2m})}\,dk\\
&=\frac{1}{2\pi}\int_{-1}^1 e^{i(kx-k^2\frac{\hbar t}{2m})}\,dk
\end{align*}\]++
When ++\(t=0\)++,
++\[\begin{align*}
\Psi(x,0)&=\frac{1}{2\pi}\int_{-1}^1 e^{ikx}\,dk\\
&=\frac{1}{2\pi}\left.\frac{e^{ikx}}{ix}\right|^{k=1}_{k=-1}\\
&=\frac{1}{2\pi ix}(e^{ix}-e^{-ix})\\
&=\frac{2i\sin(x)}{2\pi ix}\\
&=\frac{\sin(x)}{\pi x}
\end{align*}\]++
as desired.
====

* {q-num} Using the same steps as 2.4.1, find ++\(\Psi(x,t)\)++ for ++\(\Psi(x,0) = A\frac{\sin(x)}{x}\)++. You may use computational software to help you with the integrals.

* {q-num} Phase and group velocity: show that ++\(v_g-v_p=k\frac{d}{dk}v_p\)++.

* {q-num} The phase and group velocity of light:
[sublist-style]
.. Show that in a vacuum, the phase velocity and group velocity of light are the same.
.. In a medium with refractive index ++\(>1\)++ (where light travels slower than ++\(c\)++), which is greater, the phase velocity or the group velocity?

* {q-num}

== The Delta-Function Potential
=== Questions

* {q-num} For a fixed constant ++\(a\)++, compute the closed form for ++\(f(x)\coloneqq\int_{-\infty}^x\delta (t-a)\,dt\)++.

+
.Solution
[%collapsible]
====
First, use ++\(u\)++-substitution with ++\(u=t-a\)++ to obtain [.no-break]#++\(f(x)=\int_{-\infty}^{x-a} \delta(u)\,du\)++.#
Then, if ++\(x< a\)++, the integrand is everywhere 0, so ++\(f(x)=0\)++.
Meanwhile if ++\(x> a\)++, then the integrand includes ++\(\delta(0)\)++ and so ++\(f(x)=1\)++.
The value of ++\(f(a)\)++ depends on your interpretation of ++\(\int_{-\infty}^0\delta(t)\,dt\)++, which could be undefined, ++\(\frac{1}{2}\)++, or 1.
So we have
++\[\begin{align*}
f(x)&=\begin{cases}
0&x<a\\
\textrm{?}&x=a\\
1&x>a
\end{cases}
\end{align*}\]++
[sidebar]
--
Why is it so hard to define ++\(\int_{-\infty}^0\delta (t)\,dt\)++?
There are three possible values:

* Undefined, simply because by definition the only integrals of the ++\(\delta\)++ function that exist are those containing an _interval_ containing ++\(0\)++.
* ++\(\frac{1}{2}\)++, because ++\(\delta\)++ is an even "`function`", so its integral from ++\(-\infty\)++ to ++\(0\)++ should be half of its integral from ++\(-\infty\)++ to [.no-break]#++\(\infty\)++.#
* ++\(1\)++, because the domain of integration includes everywhere that [.no-break]#++\(\delta(x)\ne 0\)++.#

This helps to illustrate the thorniness of ++\(\delta\)++ and why it is not considered a function at all.
--
====

* {q-num} Show that the ++\(\delta\)++ function can be approximated by a ++\(0\)++-centered Gaussian ++\(\varphi(x)=\frac{1}{\sigma\sqrt{2\pi}}e^{-\frac{x^2}{\sigma^2}}\)++ whose variance ++\(\sigma^2\)++ approaches 0.

+
.Solution
[%collapsible]
====
Clearly, the integral of a Gaussian over the number line is 1, no matter what.
As its variance approaches 0, its integral over domains that do not include the origin must approach 0, i.e., for ++\(\varepsilon>0\)++,
++\[\begin{align*}
\lim_{\sigma^2\to0}\int_{-\infty}^{-\varepsilon}\mathcal \varphi(x)\,dx=\lim_{\sigma^2\to0}\int_{\varepsilon}^{\infty}\mathcal \varphi(x)\,dx=0
\end{align*}\]++
Since ++\(\varphi(x)>0\)++ for all ++\(x\)++, the only way the above integrals approach ++\(0\)++ as ++\(\sigma^2\to 0\)++ is if ++\(\varphi(x)\to 0\)++ for ++\(x\ne 0\)++.
Since ++\(\varphi(x)\to0\)++ when ++\(x\ne 0\)++ and ++\(\int_{-\infty}^\infty\varphi(x)\,dx=1\)++, it is indeed that case that ++\(\lim_{\sigma^2\to 0}\varphi(x)=\delta(x)\)++.
====

* {q-num} Show the following: ++\[\displaystyle\delta(x)=\lim_{k\to\infty}\frac{d}{dx}\left(\frac{1}{1+e^{-kx}}\right)\]++
This provides another continuous approximation of the ++\(\delta\)++ function which improves as ++\(k\)++ grows.
+
.Solution
[%collapsible]
====
The simplest way to show this is to observe how the expression on the RHS behaves when integrated:
++\[\begin{align*}
&\phantom{=}\int_{-\infty}^z \lim_{k\to\infty}\frac{d}{dx}\left(\frac{1}{1+e^{-kx}}\right)\,dx\\
&= \lim_{k\to\infty}\int_{-\infty}^z\frac{d}{dx}\left(\frac{1}{1+e^{-kx}}\right)\,dx\\
&= \lim_{k\to\infty}\left(\left.\frac{1}{1+e^{-kx}}\right|_{-\infty}^z\right)\\
&= \lim_{k\to\infty}\left(\frac{1}{1+e^{-kz}}-0\right)
\end{align*}\]++
When ++\(z< 0\)++, ++\(e^{-kz}\to\infty\)++ and so ++\(\frac{1}{1+e^{-kz}}\to0\)++, making the integral 0.
Meanwhile, when ++\(z>0\)++, ++\(e^{-kz}\to0\)++ and so ++\(\frac{1}{1+e^{-kz}}\to1\)++, making the integral 1.
So,
++\[\begin{align*}
\int_{-\infty}^z \lim_{k\to\infty}\frac{d}{dx}\left(\frac{1}{1+e^{-kx}}\right)\,dx&=\begin{cases}
0&z<0\\
1&z>0
\end{cases}
\end{align*}\]++
which does indeed match the ++\(\delta\)++ function.
====

* {q-num} Graph an example of:
(Show the classical turning points, ++\(E\)++, and label your axes.)
(problem may be too similar to the textbook chapter)
+
[{sublist-style}]
.. A bound state
.. A scattering state
.. A classical bound state/quantum scattering state (made
possible by quantum tunneling), and explain what quantum tunneling is.

+
.Solution
[%collapsible]
====
Graphs vary, but potential solutions on pg. 62 of Griffiths.
====

* {q-num} Derive the reflection and transmission coefficients for the delta-function well.
When are these coefficients exactly the same?

* {q-num} Describe what happens when identical waves approach the delta-potential well from _both_ sides.

* {q-num} Solve the asymmetric double delta-function potential,
++\[\begin{align*}
V(x)=\alpha \delta(x+a)+\beta\delta(x-a)
\end{align*}\]++
where ++\(\alpha\)++ and ++\(\beta\)++ are arbitrary constants (positive, negative, or zero).
When exactly one of ++\(\alpha\)++ and ++\(\beta\)++ is negative, how many bound states does this system have?

== The Finite Square Well
=== Questions

* {q-num} When is the square well approximation valid and why is it usable to make fair predictions?
+
.Solution
[%collapsible]
====
If the de Broglie wavelength of the particle
(++\(\lambda = \hbar/p\)++) ++\(<\)++
++\(\Delta x_1\)++ ++\(\Delta x_2\)++, the square well
approximation is valid.
(Unless the particle is relativistic).
Nothing we are trying to predict, like transmission and reflection coefficients,
changes after making this approximation (as long as the above condition is met).
====

* [[question-finite-well-diff-eq,2.6.2]]{q-num} Find the general solution to the finite square well differential equations for each section of the well (with ++\(V_0>0\)++):
\[V(x) = \begin{cases}
-V_0 &   |x| \le a \\
0 &  |x| > a
\end{cases}
\]
+
[{sublist-style}]
.. Left side of the well (++\(x<-a\)++)
.. Middle of the well (++\(-a\le x\le a\)++)
.. Right side of the well (++\(x>a\)++)

+
.Solution
[%collapsible]
====
[{sublist-style}]
. If ++\(V(x) = 0\)++ then the {sch} equation says ++\(-\frac{\hbar^2}{2m} \frac{d^2 \psi}{dx} = E\psi\)++.
Then ++\(\frac{d^2\psi}{dx^2}=k^2\psi\)++ where ++\(k=-\sqrt{2mE/\hbar}>0\)++ (because ++\(E< 0\)++), which has solutions of the form ++\(\psi_1(x)=Ae^{-kx} + Be^{kx}\)++.

. If ++\(V(x) = -V_0\)++ then {sch} equation says ++\(\left(-V_0-\frac{\hbar^2}{2m} \frac{d^2 \psi}{dx}\right) \psi= E\psi\)++, so ++\(\frac{d^2\psi}{dx^2}=-\frac{2m}{\hbar^2}(E+V_0)\psi\)++, which has solutions ++\(\psi_2(x)=C\sin(lx)+D\cos(lx)\)++ where ++\(l=\sqrt{2m(E+V_0)} > 0\)++.

. This is the same as part (a): ++\(\psi_3(x) = Ee^{-kx}+Fe^{kx}\)++.
====

* {q-num} Using your results from xref:question-finite-well-diff-eq[], apply the boundary conditions to all the general solutions.
Use these equations and their coefficients to derive the transcendental equation:
++\((k-il)/(k+il)= \pm e^{2ila}\)++. (Hint: ++\(k\)++ as coefficient from ++\(a\)++ and ++\(l\)++ as coefficient from ++\(b\)++.)
+
.Solution
[%collapsible]
====
The boundary conditions constitute the following:

. Finite as ++\(x\to-\infty\)++: ++\(\psi_1(x\rightarrow-\infty) < \infty\)++.
. Finite as ++\(x\to-\infty\)++:
++\(\psi_3(x\rightarrow\infty) < \infty\)++.
. Continuous at the boundaries: ++\(\psi_1(-a)=\psi_2(-a)\)++ and ++\(\psi_2(a) = \psi_3(a)\)++.
. The derivative of the wave function is continuous at boundaries:
++\[\begin{align*}
\left.\frac{d\psi_1}{dx}\right|_{x=-a} &= \left.\frac{d\psi_2}{dx}\right|_{x=-a}\\
\left.\frac{d\psi_2}{dx}\right|_{x=a} &= \left.\frac{d\psi_3}{dx}\right|_{x=a}
\end{align*}\]++

Applying these conditions to the results from xref:question-finite-well-diff-eq[]:

. ++\(\psi_1(-\infty)<\infty\)++ implies that ++\(A=0\)++ and so ++\(\psi_1(x)=Be^{kx}\)++.
. ++\(\psi_3(\infty)<\infty\)++ implies that ++\(D=0\)++ and so ++\(\psi_3(x)=Ce^{-kx}\)++.
. As in part (b) of xref:question-finite-well-diff-eq[], let ++\(\psi_2(x)=Ce\)++
++\(\frac{}{} \psi_1(x=-\infty)<\infty\)++ A=0
++\(\psi_1(x) =  Be^{kx}\)++

{empty}2. ++\(\psi_3(x=\infty)<\infty\)++ D=0
++\(\psi_3(x)=Ce^{-kx}\)++

{empty}3. Let ++\(\psi_2 = Ce^{ilx} + De^{-ilx}\)++
++\(Be^{-ka}=Ce^{-ila} + De^{ila}\)++(eq.1) and
++\(Be^{-ka} = Cile^{-ila} - Dile^{ila}\)++(eq.2) Now take:
k(eq.1) - (eq.2):
++\(Cke^{-ila} + Dke^{ila} = Cile^{-ila} - Dile^{ila}\)++
++\(C(ile^{-ila} - ke^{-ila})  = D(ke^{-ila} + ile^{ila})\)++
++\(C/D = - ((k+il)/(k-il))e^{2ila}\)++ (eq.*)

{empty}4.
++\(\psi_2(x=a)=\psi_3(x=a) an\frac{d d\psi_2}{dx}|_{x=a} = \frac{d\psi_3}{dx}|_{x=a}\)++
++\(Ce^{-ila} + De^{-ila} = Ee^{-ka}\)++(eq.3) and
++\(ilCe^{-ila}-ilDe^{-ila}=-kEe^{-ka}\)++(eq.4)

Now take: k(eq.3) + (eq.4):

++\(Cke^{-ila}+Dke^{-ila}+ilCe^{-ila}-ilDe^{-ila}=0\)++

++\(C(ke^{-ila}+ile^{-ila})=-D(ke^{-ila}-ile^{-ila})\)++

++\(C/D = - ((k+il)/(k-il))e^{-2ila}\)++ (eq.**)

Now set (eq.* = eq. **):
++\(((k+il)/(k-il))e^{2ila}=((k-il)/(k+il))e^{-2ila}\)++
++\(((k-il)/(k+il))^2=e^{4ila}\)++
++\((k-il)/(k+il) = \pm e^{2ila}\)++

====

* {q-num} {blank}
+
[{sublist-style}]
.. Calculate the transmission and reflection coefficients for xref:question-finite-well-diff-eq[].
.. What happens as ++\(T\to 1\)++ and ++\(R\to 1\)++?

* {q-num} Graph the allowed energies for the even bound state wave function of the finite square well.
Show the possible energy values and explain your reasoning.

* {q-num} Using a graphical plotting program, examine some properties of the finite height well.
[sublist-style]
.. How does the number of bound states (both odd and even) depend on the particle's mass (++\(m\)++) and the well's width (++\(a\)++) and depth (++\(V_0\)++)?
Which variable causes the number of bound states to increase the fastest?
How does this depend on the current values of ++\(m\)++, ++\(a\)++, and [.no-break]#++\(V_0\)++?#
.. In the finite height well, at the boundary of the well (++\(x=\pm a\)++), the bound states go from purely sinusoidal to exponentially decaying.
How do the values of ++\(m\)++, ++\(a\)++, ++\(V_0\)++, and the energy ++\(E\)++ of the particle affect how rapidly the bound states decay outside of the well (and in turn how likely you are to find the particle outside of the well)?


* {q-num} For what energies ++\(E=E_n+V_0\)++ is the finite square well "`opaque`" to incoming wave packets, i.e., the transmission coefficient is 0?

* {q-num} Solve the "`finite square wall`":
++\[\begin{align*}
V(x)=\begin{cases}
V_0>0&-a\le x\le a\\
0&|x|\ge a
\end{cases}
\end{align*}\]++
(Obviously there are only scattering states.)
When is the wall "`transparent`" to incoming waves?
Opaque?

* {q-num} Solve the asymmetric finite square well:
++\[\begin{align*}
V(x)=\begin{cases}
V_1&x<-a\\
0&-a\le x\le a\\
V_2&x>a
\end{cases}
\end{align*}\]++
where ++\(V_1,V_2\)++ are positive constants.
Show that when ++\(V_1=V_2\)++ you recover the solution to the symmetric finite square well.

=== Demonstrations

* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/particle_finite_height_box/particle_finite_height_box_inlined.html?t=1657044816[Finite square well stationary states (static)^]
+
NOTE: The stationary states are solved numerically in the browser (requires solving something like ++\(\tan z=\sqrt{(z_0/z)^2-1}\)++, which cannot be solved exactly), so at a handful of slider values a stationary state will be lost.
This is just a bug due to limited precision/compute time.
(Again, the universe is lucky, it gets to run its calculations to arbitrary precision in no time at all.)
