[.qm-chapter.chap-2]
= Chapter 2: Time-Independent {sch} Equation
include::shared_attributes.adoc[]

== Stationary States

* {q-num} Which of the following are always true when we use separation of variables to solve the Schrodinger equation?
.. ++\(\Psi(x,t)=\psi(x)\phi(t)\)++
.. Both sides of the Schrodinger equation are constant
.. ++\(\Psi(x,t)\)++ is a stationary state
.. ++\(V(x,t) = V(x)\)++
.. ++\(i\hbar \frac{\partial \Psi}{\partial t} = 0\)++

+
.Solution
[%collapsible]
====
Only (a) is true.
====

* {q-num} Why is ++\(\Psi_E(x,t)= \psi_E(x)e^{-iEt/\hbar}\)++ called a stationary state if it is time-dependent?
+
[{sublist-style}]
. Show that ++\(|\Psi_E(x,t)|^2 = |\psi_E(x)|^2\)++.
. Show that ++\( \Braket{p} = 0\)++ for ++\(\Psi_E(x,t)\)++.

+
.Solution
[%collapsible]
====
[{sublist-style}]
. {nbsp}
++\[\begin{align*}|
\Psi_E(x,t)|^2 &= \Psi_E^* \Psi_E\\
&= (\psi_E^*(x)e^{iEt/\hbar}) (\psi_E(x) e^{-iEt/\hbar}) \\
&= |\psi_E(x)|^2
\end{align*}\]++
. For a particle in state ++\(\Psi_E\)++,
++\[\begin{align*}
\Braket{x}&=\int_{\mathcal D} x|\Psi_E(x,t)|^2 \,dx\\
&=\int_{\mathcal D} x|\psi_E(x)|^2\,dx\\
&=\textrm{constant w.r.t time}
\end{align*}\]++
So ++\(\frac{d\Braket{x}}{dt}=0\)++.
Then, Ehrenfest's theorem says that ++\(\Braket{p}=m\frac{d\Braket{x}}{dt}=0\)++.

====


* {q-num} [Similar to Griffiths text (not a problem). Need to modify more]
The classical Hamiltonian, the total energy in a system, is given by ++\(H(x,p)=\frac{p^2}{2m}+V(x)\)++, where ++\(\frac{p^2}{2m}\)++ is the kinetic energy and ++\(V(x)\)++ is the potential energy.
+
[{sublist-style}]
** Using the quantum mechanical substitution rule ++\(p \rightarrow -i\hbar \frac{\partial}{\partial x}\)++, find the quantum mechanical Hamiltonian ++\(\hat H\)++.
Substituting this Hamiltonian into the time-independent {sch} equation
++\[-\frac{\hbar^2}{2m}\frac{d^2\psi}{dx^2}+V\psi = E\psi\]++
yields ++\(\hat H\psi=E\psi\)++.
** Show that ++\(\Braket{\hat H} = E\)++.
** Show that ++\(\Braket{\hat H^2} = E^2\)++. (Hint: first show that ++\(\hat H^2\psi=E^2\psi\)++)
** Conclude that the variance of ++\(\hat H\)++ is 0.

+
In other words, every measurement of the total energy of a solution to the time-dependent {sch} equation will yield ++\(E\)++.



* {q-num} If you were to measure the energy of a particle with the wavefunction ++\(\Psi(x,t) = \frac{4}{5}\Psi_1(x,t) - \frac{3i}{5} \Psi_2(x,t)\)++, what is the probability that you’d measure the energy to be ++\(E_2\)++?

* {q-num} Griffiths's questions 2.1 and 2.2 are very good. Check to see how those can be modified.


== The Infinite Square Well
=== Questions

* {q-num} The solutions to the time-independent {sch} equation in the infinite square well of width \(a\) are ++\(\psi_n(x)=\sqrt{2/a}\sin\left(\frac{n\pi}{a}x\right)\)++ with ++\(n\ge 1\)++.
Show that these functions are _orthonormal_, i.e., that ++\(\Braket{\psi_m,\psi_n}\)++ is 1 when ++\(m=n\)++ and 0 otherwise.
(Hint: ++\(\cos\)++ is an even function, ++\(\sin\)++ is an odd function, and ++\(\cos(a+b)=\cos a\cos b-\sin a\sin b\)++.)
+
.Solution
[%collapsible]
====
Using the trigonometric identities in the hint, we have
++\[\begin{align*}
\cos(a+b)&=\cos a\cos b-\sin a\sin b\\
\cos(a-b)&=\cos a\cos b+\sin a\sin b\\
\cos(a+b)-\cos(a-b)&=-2\sin a\sin b\\
\sin a \sin b &=\frac{1}{2}(\cos(a-b) - \cos(a+b))
\end{align*}\]++
Regardless of whether ++\(m=n\)++,
++\[\begin{align*}
\Braket{\psi_m,\psi_n}&= \int_0^a \psi_m^*\psi_n\,dx\\
&=\int_0^a \sqrt\frac{2}{a}\sin\left(\frac{m\pi}{a}x\right)\ \sqrt\frac{2}{a}\sin\left(\frac{n\pi}{a}x\right)\,dx\\
&=\frac{1}{a}\int_0^a \cos\left(\frac{(m-n)\pi}{a}x\right)-\cos\left(\frac{(m+n)\pi}{a}x\right)\,dx
\end{align*}\]++
And for ++\(k\ne 0\)++,
++\[\begin{align*}
\int_0^a \cos\left(\frac{k\pi}{a}x\right)\,dx=\left.\frac{a}{k\pi}\sin\left(\frac{k\pi}{a}x\right)\right|^a_0=0
\end{align*}\]++
When ++\(m=n\)++, ++\(\Braket{\psi_m,\psi_n}\)++ becomes
++\[\begin{align*}
\frac{1}{a}\int_0^a \cos 0-\cos\left(\frac{(m+n)\pi}{a}x\right)\,dx=\frac{1}{a}\int_0^a dx=1
\end{align*}\]++
When ++\(m\ne n\)++, both of the ++\(\cos\)++ terms in the integral are of the form ++\(\cos\left(\frac{k\pi}{a}x\right),k\ne 0\)++ and so they both integrate to 0, and then ++\(\Braket{\psi_m,\psi_n}=0\)++.
====

* {q-num} Let ++\(V\)++ be the potential in the infinite square well:
\[V(x) = \begin{cases}
            0 &  0 \leq x \leq a \\
            \infty &  \textrm{otherwise}
\end{cases}
\]
+
[{sublist-style}]
.. Find the general solution using the time-independent {sch} equation, the simple harmonic oscillator equation, and applying the constraints of the infinite square well.
.. Apply the boundary conditions to solve for the constants ++\(A\)++ and ++\(B\)++.
.. Find solutions for ++\(kx\)++ and, using those results, solve for the possible values of the energy ++\(E\)++.
.. How does this result compare to what we’d expect from a classical case?
.. Use this result and normalize ++\(\Psi\)++ to solve for stationary states.
.. What is the significance of this result?

+
.Solution
[%collapsible]
====
[{sublist-style}]
. Inside the well, ++\(V(x) = 0\)++, and so the {sch} equation says ++\(\frac{-\hbar^2}{2m}\frac{\partial^2\psi}{\partial x^2}=E\psi(x)\)++.
Letting ++\(k=\sqrt{2mE/\hbar}\)++, we have
++\(\frac{d^2\psi(x)}{dx^2}= -k^2\psi(x)\)++.
 Assuming ++\(E\geq0\)++, the
solution isn’t contradicting the boundary conditions. Recognize:
++\(\frac{d^2\psi(x)}{dx^2} + k^2\psi = 0\)++ as the equation of the
simple harmonic oscillator.
The solution of this equation is
++\(\psi(x)=A\sin(kx)+B\cos(kx)\)++ where ++\(A,B\)++ are constants determined by the boundary conditions.

. For ++\(\psi\)++ to be continuous at ++\(0\)++ and ++\(a\)++, we must have ++\(\psi(0) =\psi(a)=0\)++.
So ++\(\psi(0) = A\sin(0) + B\cos(0) = B\)++, and hence
++\(B=0\)++.
This leaves us with: ++\(\psi(x)=A\sin(kx)\)++,
so either ++\(A=0\)++ — in which case ++\(\psi\)++ is 0 everywhere, which is not a valid wavefunction — or ++\(\sin(ka)=0\)++.
. The boundary condition ++\(\psi(a)=A\sin(ka)=0\)++ requires that ++\(k= \frac{n\pi}{a}\)++ with ++\(n\)++ an integer.
But if ++\(n=0\)++ then ++\(\psi(x)=0\)++ everywhere, so ++\(n\)++ must in fact be nonzero.
Additionally, ++\(\sin\left(\frac{-n\pi}{a}x\right)=-\sin\left(\frac{n\pi}{a}x\right)\)++ — a solution we've already accounted for, since ++\(A\)++ can absorb the leading minus sign — so the distinct solutions are ++\(k= \frac{n\pi}{a}\)++ for positive integer ++\(n\)++.
Therefore the permissible values of the energy ++\(E\)++ are
++\(E_n=\frac{\hbar^2 k_n^2}{2m} =\frac{\pi^2 n^2\hbar^2}{2ma^2}\)++ with ++\(n\)++ a positive integer.

. Unlike the classical case, a quantum particle in the infinite square well cannot have an arbitrary value of energy.
Instead, a quantum particle can only be in a superposition of one of these special _allowed_ states that fit within the constraints of the infinite square well.
When observed, a quantum particle in the infinite square well will have an energy that is one of the ++\(E_n\)++.
. To compute the integral, we'll need the fact that ++\(\sin^2(a)=\frac{1}{2}(1-\cos(2a))\)++.
++\[\begin{align*}
|\psi_n(x)|^2&=\int_0^a |A|^2\sin^2\left(\frac{n\pi}{a}x\right)\,dx\\
&=|A|^2\int_0^a\frac{1}{2}\left[1-\cos\left(\frac{2n\pi}{a}x\right)\right]\,dx\\
&=\frac{|A|^2}{2}\left.\left[x-\frac{\sin(\frac{2n\pi}{a}x)}{\frac{2n\pi}{a}}\right]\right|^a_0\\
&=\frac{|A|^2a}{2}
\end{align*}\]++
For the norm to be 1, we must have ++\(|A|=\sqrt{\frac{2}{a}}\)++.
Any choice of ++\(A\)++ satisfying this will do — ++\(A\)++ can be complex, but its phase doesn't matter — so let's pick the most obvious and simplest choice, ++\(A=\sqrt{\frac{2}{a}}\)++, to obtain ++\(\psi_n(x)=\sqrt\frac{2}{a}\sin\left(\frac{\pi}{a}x\right)\)++.
(In general, it's always simplest to choose the stationary states that are real-valued.)

====

* {q-num} What are the four properties of the functions
++\(\Psi_n(x)\)++?
Are these properties unique to the infinite square well?
Why are they so important?
+
.Solution
[%collapsible]
====
. These functions are alternatively even and odd about
the center of the potential well.
This is true for any symmetrical potential well.
. With increasing ++\(n\)++, each successive state has one more node in the wavefunction.
This is true regardless of the shape of the potential well.
. They are mutually orthogonal: ++\(\int \psi_m(x)^*\psi_n(x)\,dx=\delta_{mn}\)++. This is true regardless of the potential well, as
long as it's normalized.
. The state functions form a complete set. This is not
universal, but is almost always applicable for any potential we will
encounter.

These properties are so important because they hold true for almost all potentials, which means we can apply these four properties to help solve many different types of problems.
====

* {q-num} A particle in the infinite square well has an initial wave function with an even combination of the first three stationary states: ++\(\Psi(x,0)=A(\psi_1(x) + \psi_2(x) + \psi_3(x))\)++.
+
[{sublist-style}]
.. Normalize to find A.
.. Find ++\(c_n\)++ and ++\(\psi(x,t)\)++. (Hint: let ++\(\omega=\pi^2\hbar/2ma^2\)++.)
.. Find ++\(|\Psi(x,t)|^2\)++.
.. Find {expect-x}.
What is the frequency of oscillations?
What is the amplitude?

+
.Solution
[%collapsible]
====
Unsure if this is possible, I may have to re-write with two stationary states w/ coefficients.
====


== The Harmonic Oscillator

=== Questions

* {q-num} Show that every solution of the time-independent harmonic oscillator {sch} equation ++\(\hat H\psi = E\psi\)++ lies on the same "`ladder`": for every pair of solutions ++\(\psi_a,\psi_b\)++, there is some \(n\) for which ++\(\psi_a=\hat a_{\pm}^n\psi_b\)++.
+
NOTE: I actually don't know if this is possible with the ladder operators alone, or if you have to actually solve the {sch} equation in its entirety to deduce that the ladder operators give _all_ the solutions.
+
.Solution (placeholder)
[%collapsible]
====
{blank}
====

* {q-num} For small displacements, the harmonic oscillator is a good second-order approximation of many potential fields.
What is an example of a potential field ++\(V(x)\)++ for which the harmonic oscillator is _not_ a good approximation?
+
.Solution
[%collapsible]
====
++\(V(x)=x^4\)++ is one such potential, as it has no quadratic terms.
====

* {q-num} [Thaller] Show that any solution ++\(\Psi\)++ of the harmonic oscillator satisfies ++\(\Psi(x,t+\pi)=e^{-i\pi/2}\Psi(-x,t)\)++. (Corollary: ++\(\Psi(x,t+2\pi)=-\Psi(-x,t)\)++.)

* {q-num} Show that in the harmonic oscillator, ++\(\dot p=-kx\)++.

* {q-num} [Adapted from Griffiths 2.16]
The *Rodrigues formula* says that ++\(H_n(x)=(-1)^n e^{x^2}\frac{d^n}{dx^n}(e^{-x^2})\)++.
+
[{sublist-style}]
** Use this to derive the recurrence relation ++\(H_{n+1}(x)=2xH_n(x)-2nH_{n-1}(x)\)++.
** Show that ++\(H_n\)++ satisfies ++\(\frac{d H_n(x)}{dx}=2nH_{n-1}(x)\)++.
** Show that ++\(H_n(x)=\left.\frac{d^n}{dz^n}(e^{-z^2+2zx})\right|_{z=0}\)++.

:!qn:
=== Demonstrations

* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/harmonic_oscillator/harmonic_oscillator_inlined.html?t=1657044816[Harmonic oscillator stationary states (static)^]
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/harmonic_oscillator/harmonic_oscillator_evolution_inlined.html?t=1657044816[Harmonic oscillator evolution over time^]

== The Free Particle

* {q-num} Suppose a free particle has the initial wavefunction ++\(\psi(x) = \frac{\sin(x)}{\pi x}\)++.
(Take our word for it that this wavefunction is already normalized.)
[{sublist-style}]
. Find ++\(F(k):=\mathcal{F}[\psi](k)\)++.
You may use computational software to help you calculate the integral.
(But don't just type in "`Fourier transform of ++\(\frac{\sin(x)}{\pi x}\)++`"!)
. Verify that your result satisfies ++\(\Psi(x,0)=\frac{\sin(x)}{\pi x}\)++.
. Find ++\(\Psi(x,t)\)++.

+
.Solution
[%collapsible]
====
[{sublist-style}]
. {nbsp}
++\[\begin{align*}
F(k)&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty \psi(x)e^{-ikx}\,dx\\
&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty \frac{1}{\pi} \ \frac{\sin(x)e^{-ikx}}{x}\,dx\\
&= \textrm{(... computational software ...)}\\
&=\frac{1}{\pi\sqrt{2\pi}}\begin{cases}\pi&-1<k<1\\
0&\textrm{otherwise}
\end{cases}\\
&=\begin{cases}\frac{1}{\sqrt{2\pi}}&-1<k<1\\
0&\textrm{otherwise}
\end{cases}
\end{align*}\]++

. For all ++\(t\)++,
++\[\begin{align*}
\Psi(x,t)&=\frac{1}{\sqrt{2\pi}}\int_{-\infty}^\infty F(k)e^{i(kx-\frac{\hbar k^2}{2m}t)}\,dk\\
&=\frac{1}{\sqrt{2\pi}}\int_{-1}^1 \frac{1}{\sqrt{2\pi}}e^{i(kx-k^2\frac{\hbar t}{2m})}\,dk\\
&=\frac{1}{2\pi}\int_{-1}^1 e^{i(kx-k^2\frac{\hbar t}{2m})}\,dk
\end{align*}\]++
When ++\(t=0\)++,
++\[\begin{align*}
\Psi(x,0)&=\frac{1}{2\pi}\int_{-1}^1 e^{ikx}\,dk\\
&=\frac{1}{2\pi}\left.\frac{e^{ikx}}{ix}\right|^{k=1}_{k=-1}\\
&=\frac{1}{2\pi ix}(e^{ix}-e^{-ix})\\
&=\frac{2i\sin(x)}{2\pi ix}\\
&=\frac{\sin(x)}{\pi x}
\end{align*}\]++
as desired.
Now we'll find ++\(\Psi(x,t)\)++ for ++\(t\ne 0\)++.
Defining the special _error function_ ++\(\textrm{erf} (z):=\frac{2}{\sqrt \pi}\int_0^z e^{-t^2/2}\,dt\)++,
++\[\begin{align*}
\Psi(x,t)&=\frac{1}{2\pi}\int_{-1}^1 e^{i(kx-k^2\frac{\hbar t}{2m})}\,dk\\
&=\textrm{(... computational software ...)}\\
&=
\end{align*}\]++
a)

++\(\int_{-\infty}^{\infty} |\Psi(x,0)|^2 dx\)++ = 1 =
++\(|A|^2 \int_{-\infty}^\infty sin^2x/x^2 dx\)++ =
++\(|A|^2\pi\)++ |A|++\(^2 = 1/\pi\)++
A=1/++\(\sqrt{\pi}\)++

{empty}b)
++\(\phi(k) = (1/\sqrt{2\pi}) (1/\sqrt{\pi}) \int_{-\infty}^{\infty} (sinx/x) e^{ikx} dx =\)++

{empty}c)
++\(\Psi(x,t) = 1/\sqrt{2\pi}\int_{-\infty}^{\infty} \phi(k)e^{i(kx-(\hbar k^2t/2m))} dk\)++
(as far as I made it on 2.4.1...)

====

* {q-num} Using the same steps as 2.4.1, find ++\(\Psi(x,t)\)++ for ++\(\Psi(x,0) = A\frac{\sin(x)}{x}\)++. You may use computational software to help you with the integrals.

* {q-num} Phase and group velocity

* {q-num}

* {q-num}

:!qn:

== The Delta-Function Potential
=== Questions

* {q-num} Graph an example of:
(Show the classical turning points, ++\(E\)++, and label your axes.)
(problem may be too similar to the textbook chapter)
+
[{sublist-style}]
.. A bound state
.. A scattering state
.. A classical bound state/quantum scattering state (made
possible by quantum tunneling), and explain what quantum tunneling is.

+
.Solution
[%collapsible]
====
Graphs vary, but potential solutions on pg. 62 of Griffiths.
====

* {q-num} Derive the reflection and transmission coefficients for the delta-function well.
When are these coefficients exactly the same?


== The Finite Square Well
=== Questions

* {q-num} When is the square well approximation valid and why is it usable to make fair predictions?
+
.Solution
[%collapsible]
====
If the de Broglie wavelength of the particle
(++\(\lambda = \hbar/p\)++) ++\(<\)++
++\(\Delta x_1\)++ ++\(\Delta x_2\)++, the square well
approximation is valid.
(Unless the particle is relativistic).
Nothing we are trying to predict, like transmission and reflection coefficients,
changes after making this approximation (as long as the above condition is met).
====

* [[question-finite-well-diff-eq,2.6.2]]{q-num} Find the general solution to the finite square well differential equations for each section of the well (with ++\(V_0>0\)++):
\[V(x) = \begin{cases}
-V_0 &   |x| \le a \\
0 &  |x| > a
\end{cases}
\]
+
[{sublist-style}]
.. Left side of the well (++\(x<-a\)++)
.. Middle of the well (++\(-a\le x\le a\)++)
.. Right side of the well (++\(x>a\)++)

+
.Solution
[%collapsible%open]
====
[{sublist-style}]
. If ++\(V(x) = 0\)++ then the {sch} equation says ++\(-\frac{\hbar^2}{2m} \frac{d^2 \psi}{dx} = E\psi\)++.
Then ++\(\frac{d^2\psi}{dx^2}=k^2\psi\)++ where ++\(k=-\sqrt{2mE/\hbar}>0\)++ (because ++\(E< 0\)++), which has solutions of the form ++\(\psi_1(x)=Ae^{-kx} + Be^{kx}\)++.

. If ++\(V(x) = -V_0\)++ then {sch} equation says ++\(\left(-V_0-\frac{\hbar^2}{2m} \frac{d^2 \psi}{dx}\right) \psi= E\psi\)++, so ++\(\frac{d^2\psi}{dx^2}=-\frac{2m}{\hbar^2}(E+V_0)\psi\)++, which has solutions ++\(\psi_2(x)=C\sin(lx)+D\cos(lx)\)++ where ++\(l=\sqrt{2m(E+V_0)} > 0\)++.

. This is the same as part (a): ++\(\psi_3(x) = Ee^{-kx}+Fe^{kx}\)++.
====

* {q-num} Using your results from xref:question-finite-well-diff-eq[], apply the boundary conditions to all the general solutions.
Use these equations and their coefficients to derive the transcendental equation:
++\((k-il)/(k+il)= \pm e^{2ila}\)++. (Hint: ++\(k\)++ as coefficient from ++\(a\)++ and ++\(l\)++ as coefficient from ++\(b\)++.)
+
.Solution
[%collapsible%open]
====
The boundary conditions constitute the following:

. Finite as ++\(x\to-\infty\)++: ++\(\psi_1(x\rightarrow-\infty) < \infty\)++.
. Finite as ++\(x\to-\infty\)++:
++\(\psi_3(x\rightarrow\infty) < \infty\)++.
. Continuous at the boundaries: ++\(\psi_1(-a)=\psi_2(-a)\)++ and ++\(\psi_2(a) = \psi_3(a)\)++.
. The derivative of the wave function is continuous at boundaries:
++\[\begin{align*}
\left.\frac{d\psi_1}{dx}\right|_{x=-a} &= \left.\frac{d\psi_2}{dx}\right|_{x=-a}\\
\left.\frac{d\psi_2}{dx}\right|_{x=a} &= \left.\frac{d\psi_3}{dx}\right|_{x=a}
\end{align*}\]++

Applying these conditions to the results from xref:question-finite-well-diff-eq[]:

. ++\(\psi_1(-\infty)<\infty\)++ implies that ++\(A=0\)++ and so ++\(\psi_1(x)=Be^{kx}\)++.
. ++\(\psi_3(\infty)<\infty\)++ implies that ++\(D=0\)++ and so ++\(\psi_3(x)=Ce^{-kx}\)++.
. As in part (b) of xref:question-finite-well-diff-eq[], let ++\(\psi_2(x)=Ce\)++
++\(\frac{}{} \psi_1(x=-\infty)<\infty\)++ A=0
++\(\psi_1(x) =  Be^{kx}\)++

{empty}2. ++\(\psi_3(x=\infty)<\infty\)++ D=0
++\(\psi_3(x)=Ce^{-kx}\)++

{empty}3. Let ++\(\psi_2 = Ce^{ilx} + De^{-ilx}\)++
++\(Be^{-ka}=Ce^{-ila} + De^{ila}\)++(eq.1) and
++\(Be^{-ka} = Cile^{-ila} - Dile^{ila}\)++(eq.2) Now take:
k(eq.1) - (eq.2):
++\(Cke^{-ila} + Dke^{ila} = Cile^{-ila} - Dile^{ila}\)++
++\(C(ile^{-ila} - ke^{-ila})  = D(ke^{-ila} + ile^{ila})\)++
++\(C/D = - ((k+il)/(k-il))e^{2ila}\)++ (eq.*)

{empty}4.
++\(\psi_2(x=a)=\psi_3(x=a) an\frac{d d\psi_2}{dx}|_{x=a} = \frac{d\psi_3}{dx}|_{x=a}\)++
++\(Ce^{-ila} + De^{-ila} = Ee^{-ka}\)++(eq.3) and
++\(ilCe^{-ila}-ilDe^{-ila}=-kEe^{-ka}\)++(eq.4)

Now take: k(eq.3) + (eq.4):

++\(Cke^{-ila}+Dke^{-ila}+ilCe^{-ila}-ilDe^{-ila}=0\)++

++\(C(ke^{-ila}+ile^{-ila})=-D(ke^{-ila}-ile^{-ila})\)++

++\(C/D = - ((k+il)/(k-il))e^{-2ila}\)++ (eq.**)

Now set (eq.* = eq. **):
++\(((k+il)/(k-il))e^{2ila}=((k-il)/(k+il))e^{-2ila}\)++
++\(((k-il)/(k+il))^2=e^{4ila}\)++
++\((k-il)/(k+il) = \pm e^{2ila}\)++

====

* {q-num} {blank}
+
[{sublist-style}]
.. Calculate the transmission and reflection coefficients for xref:question-finite-well-diff-eq[].
.. What happens as ++\(T\to 1\)++ and ++\(R\to 1\)++?

* {q-num} Graph the allowed energies for the even bound state wave function of the finite square well.
Show the possible energy values and explain your reasoning.

* {q-num} How do the amount of bound states change based on the depth of the well?
How does a wide, deep well differ from a shallow, narrow well?

=== Demonstrations

* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/particle_finite_height_box/particle_finite_height_box_inlined.html?t=1657044816[Finite square well stationary states (static)^]
+
NOTE: The stationary states are solved numerically in the browser (requires solving something like ++\(\tan z=\sqrt{(z_0/z)^2-1}\)++, which cannot be solved exactly), so at a handful of slider values a stationary state will be lost.
This is just a bug due to limited precision/compute time.
(Again, the universe is lucky, it gets to run its calculations to arbitrary precision in no time at all.)
