[.qm-chapter.chap-3]
= Chapter 3: Formalism
include::shared_attributes.adoc[]

== Hilbert Space

=== Questions

* *{q-num}*
A function ++\(f\)++ is said to absolutely integrable when ++\(|f|\)++ is integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is absolutely integrable, but not square-integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is square-integrable, but not absolutely integrable.abcd

+
.Solution
[%collapsible]
====
The "`trick`" is find functions that approach the x- or y-axis quickly enough to have a finite integral, but no longer do so when squared (part (a)) or square-rooted (part (b)).

[{sublist-style}]
. One example is
++\[\begin{align*}
f(x)=\begin{cases}
|x|^{-\frac{1}{2}}-1&|x|\le1\\
0&|x|>1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f1.svg[A function that is integrable but not square-integrable,width=500,role="text-center"]
+
This is because ++\(\int_0^1 x^n\,dx\)++ is finite if and only if ++\(n > -1\)++.
So ++\(x^{-\frac{1}{2}}\)++ is integrable, but its square, ++\(x^{-1}\)++, is not.

. One example is
++\[\begin{align*}
f(x)=\begin{cases}
\frac{1}{|x|}&|x|\ge1\\
1&|x|<1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f2.svg[A function that is square-integrable but not integrable,width=500,role="text-center"]
+
This is because ++\(\int_1^\infty x^n\,dx\)++ is finite if and only if ++\(n<-1\)++.
So ++\(x^{-1}\)++ is not integrable, but its square, ++\(x^{-2}\)++, is.
====

=== Demonstrations

== Observables

=== Questions
* *{q-num}* Show that if ++\(P=Q^\dagger Q\)++ for some operator ++\(Q\)++, then ++\(\langle f|Pf\rangle\ge 0\)++ for all ++\(f\)++.
+
.Solution
[%collapsible]
====
If ++\(Q\)++ is defined on domain ++\(\mathcal D\)++, then
++\[
\begin{align*}
\langle f|Pf\rangle&=\langle f|Q^\dagger Qf\rangle\\
&=\langle Qf| Qf\rangle\\
&=\int_\mathcal{D} |Qf|^2\,dx
\end{align*}
\]++

Since ++\(|Qf|^2\)++ is nonnegative, so is any integral of it.
====

* *{q-num}* Show that ++\(Q^{\dagger\dagger}=Q\)++ for any operator ++\(Q\)++. (In other words, show that the adjoint of the adjoint is the original operator.)
+
.Solution
[%collapsible]
====
Simply by the definition of the adjoint and the fact that ++\(\langle g|f\rangle=\langle f|g\rangle^*\)++, we have, for all ++\(f\)++ and ++\(g\)++,
++\[
\begin{align*}
\langle Q^{\dagger\dagger} f|g\rangle&=\langle f|Q^\dagger g\rangle\\
&=\langle Q^\dagger g|f\rangle^*\\
&=\langle g|Qf\rangle^*\\
&=\langle Qf|g\rangle^{**}\\
&=\langle Qf|g\rangle
\end{align*}
\]++

Now, because the inner product is linear,
++\[
\begin{align*}
0&=\langle Q^{\dagger\dagger} f|g\rangle-\langle Qf|g\rangle\\
&=\langle Q^{\dagger\dagger} f-Qf|g\rangle\\
&=\langle (Q^{\dagger\dagger} -Q)f|g\rangle
\end{align*}
\]++

In particular, taking ++\(g=(Q^{\dagger\dagger} -Q)f\)++, we have

++\[
\begin{align*}
0&=\langle (Q^{\dagger\dagger} -Q)f|(Q^{\dagger\dagger} -Q)f\rangle\\
&=|(Q^{\dagger\dagger} -Q)f|^2
\end{align*}
\]++

Hence ++\((Q^{\dagger\dagger} -Q)f=\vec 0\)++ (0⃗ the vector/function, not 0 the number).
Since ++\(f\)++ was arbitrary, ++\(Q^{\dagger\dagger} -Q\)++ must be the zero operator, and so ++\(Q^{\dagger\dagger} =Q\)++.
====

== Eigenfunctions of a Hermitian Operator

=== Questions

* *{q-num}* find the eigenfunctions and eigenvalues of the position operator ++\(x\)++, defined by ++\(x(f)=xf\)++, and ++\(p\)++, defined by ++\(p(f)=-i\hbar \frac{\partial f}{\partial x}\)++.

* *{q-num}* Suppose that ++\(f\)++ is an eigenfunction of operators ++\(Q_1\)++ and ++\(Q_2\)++ with eigenvalues ++\(q_1\)++ and ++\(q_2\)++, respectively.
Show that ++\(f\)++ is an eigenfunction of the following operators, and find the corresponding eigenvalues.
. ++\(\alpha Q_1\)++ for ++\(\alpha\in\mathbb C \)++
. ++\(Q_1+Q_2\)++
. ++\(Q_1Q_2\)++
. ++\(Q_2Q_1\)++

+
.Solution
[%collapsible]
====
The following laws are helpful:

* Operator application is associative
* Operator application distributes over addition
* Scalars commute with everything

//

. ++\(((\alpha Q_1)f=\alpha (Q_1f)=\alpha q_1f\)++, so ++\(f\)++ is an eigenfunction of ++\(\alpha Q_1\)++ with eigenvalue ++\(\alpha q_1\)++.
. ++\((Q_1+Q_2)f=Q_1f+Q_2f=q_1f+q_2f=(q_1+q_2)f\)++, so ++\(f\)++ is an eigenfunction of ++\(Q_1+Q_2\)++ with eigenvalue ++\(q_1+q_2\)++.
.
++\[
\begin{align*}
(Q_1Q_2)f&=Q_1(Q_2f)\\
&=Q_1(q_2f)\\
&=q_2(Q_1f)\\
&=q_2q_1f
\end{align*}
\]++
So ++\(f\)++ is an eigenfunction of ++\(Q_1Q_2\)++ with eigenvalue ++\(q_1q_2\)++
. The proof proceeds exactly as above. The eigenvalue is again ++\(q_1q_2\)++. So, while operators may not commute, the eigenvalues of the product of two operators does not depend on the order of the product.
====

* *{q-num}* Find the eigenfunctions and eigenvalues of the operator ++\(\frac{d^n}{dx^n}\)++ for positive integer ++\(n\)++.
(Don't worry about whether the solutions are square-integrable.)
+
.Solution
[%collapsible]
====
For fixed ++\(q\ne 0\)++, solving ++\(\frac{d^n}{dx^n}f(x)=qf(x)\)++ yields
++\[ f_q(x)=\sum_{k=1}^{n}c_k \exp\left[(-1)^{2k/n}q^{1/n}x\right] \]++
where ++\(f_q\)++ is the eigenfunction belonging to eigenvalue ++\(q\)++, and the ++\(c_k\)++ are constants determined by the boundary conditions.
Evidently, every nonzero complex number is an eigenvalue.

If ++\(q=0\)++, then the solutions to ++\(\frac{d^n}{dx^n}f(x)=0\)++ are simply the polynomials of degree at most ++\(n-1\)++.

NOTE: This problem highlights the fact that the eigenfunctions of an operator depend on the _precise_ operator in question; ++\(\frac{d^n}{dx^n}-q\)++ is quite different from ++\(\frac{d^n}{dx^n}\)++ when ++\(q\ne0\)++.
====

== Generalized Statistical Interpretation

== The Uncertainty Principle

== Vectors and Operators

=== Questions

* *{q-num}* Find the eigenvalues and normalized eigenvectors of
++\[M=\begin{pmatrix}4&2\\1&5\end{pmatrix}\]++
+
.Solution
[%collapsible%open]
====
The characteristic polynomial of ++\(M\)++ is
++\[\begin{align*}
0&=(4-x)(5-x)-1\cdot 2\\&=x^2-9x+18\\&=(x-3)(x-6)
\end{align*}\]++
So the eigenvalues are 3 and 6.
====

* *{q-num}* What are the eigenvalues and normalized eigenvectors of a diagonal matrix with diagonal entries ++\(m_1, \ldots, m_n\)++?
