= Chapter 2
include::shared_attributes.adoc[]

== Stationary States

* *2.1.{counter:qn}* Which of the following are always true when we use separation of variables to solve the Schrodinger equation?
** ++\(\Psi(x,t)=\psi(x)\phi(t)\)++
** Both sides of the Schrodinger equation are constant
** ++\(\Psi(x,t)\)++ is a stationary state
** ++\(V(x,t) = V(x)\)++
** ++\(i\hbar \frac{\partial \Psi}{\partial t} = 0\)++


* *2.1.{counter:qn}* Why is ++\(\Psi(x,t)\)++ called a stationary state if it is time-dependent?
+
[{sublist-style}]
. Show that ++\(|\Psi(x,t)|^2 = |\psi(x)|^2\)++
. Show that ++\( \langle p \rangle = 0\)++ for ++\(\Psi(x,t) = \psi(x)e^{-iEt/\hbar}\)++


* *2.1.{counter:qn}* The classical Hamiltonian, the total energy in a system, is given by ++\(H(x,p)=\frac{p^2}{2m}+V(x)\)++, where ++\(\frac{p^2}{2m}\)++ is the kinetic energy and ++\(V(x)\)++ is the potential energy.
+
[{sublist-style}]
** Using the quantum mechanical substitution rule ++\(p \rightarrow -i\hbar \frac{\partial}{\partial x}\)++, find the quantum mechanical Hamiltonian ++\(\hat H\)++.
Substituting this Hamiltonian into the time-independent {sch} equation
++\[-\frac{\hbar^2}{2m}\frac{d^2\psi}{dx^2}+V\psi = E\psi\]++
yields ++\(\hat H\psi=E\psi\)++.
** Show that ++\(\langle \hat H \rangle = E\)++.
** Show that ++\(\langle \hat H^2 \rangle = E^2\)++. (Hint: first show that ++\(\hat H^2\psi=E^2\psi\)++)
** Conclude that the variance of ++\(\hat H\)++ is 0.

+
In other words, every measurement of the total energy of a solution to the time-dependent {sch} equation will yield ++\(E\)++.



* *2.1.{counter:qn}* If you were to measure the energy of a particle with the wavefunction ++\(\Psi(x,t) = \frac{4}{5}\Psi_1(x,t) - \frac{3i}{5} \Psi_2(x,t)\)++, what is the probability that you’d measure the energy to be ++\(E_2\)++?

* *2.1.{counter:qn}* Griffiths's questions 2.1 and 2.2 are very good. Check to see how those can be modified.

:!qn:
== The Infinite Square Well

* *2.2.{counter:qn}* The solutions to the time-independent {sch} equation in the infinite square well of width \(a\) are ++\(\psi_n(x)=\sqrt{2/a}\sin\left(\frac{n\pi}{a}x\right)\)++.
Show that these functions are _orthonormal_, i.e., that ++\(\langle \psi_m,\psi_n\rangle\)++ is 1 when ++\(m=n\)++ and 0 otherwise.
(Hint: ++\(\cos\)++ is an even function, ++\(\sin\)++ is an odd function, and ++\(\cos(a+b)=\cos a\cos b-\sin a\sin b\)++.)

:!qn:
== The Harmonic Oscillator

* Griffiths
** *2.3.{counter:qn}*
+
[{sublist-style}]
. Compute ++\(\psi_2(x)\)++. (Hint: ++\(\psi_{n+1}=\frac{\hat a_+}{\sqrt{n+1}\psi_n\)++)
. Sketch ++\(\psi_0(x)\)++, ++\(\psi_1(x)\)++, and ++\(\psi_2(x)\)++.
. Check the orthogonality of , and , by explicit integration.
(Hint: If you exploit the even-ness and odd-ness of the functions, there is really only one integral left to do.)

** *2.3.{counter:qn}*
+
[{sublist-style}]
. Compute {expect-x}, {expect-p}, {expect-x2} and {expect-p2}, for the states ++\(\psi_0\)++ (Equation 2.60) and ++\(\psi_1\)++ (Equation 2.63), by explicit integration.
_Comment_: In this and other problems involving the harmonic oscillator it simplifies matters if you introduce the variable ++\(\xi =\sqrt{\frac{m\omega}{\hbar x}}\)++ and the constant ++\(\alpha=\left(\frac{m\omega}{\pi\hbar}\right)^\frac{1}{4}\)++
. Check the uncertainty principle for these states.
. Compute {xl}T{xr} and {xl}V{xr} for these states. (No new integration allowed!) Is their sum what you would expect?

:!qn:
== The Free Particle

* *2.4.{counter:qn}* Find ++\(\Psi(x,t)\)++ given ++\(\Psi(x,0) = \)++



* *2.4.{counter:qn}*

* *2.4.{counter:qn}*

* *2.4.{counter:qn}*

* *2.4.{counter:qn}*

:!qn:

== The Delta-Function Potential



== The Finite Square Well