[.qm-chapter.chap-3]
= Chapter 3: Formalism
include::shared_attributes.adoc[]

== Hilbert Space

=== Questions

* {q-num}
A function ++\(f\)++ is said to absolutely integrable when ++\(|f|\)++ is integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is absolutely integrable, but not square-integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is square-integrable, but not absolutely integrable.

+
.Solution
[%collapsible]
====
The "`trick`" is find functions that approach the x- or y-axis quickly enough to have a finite integral, but no longer do so when squared (part (a)) or square-rooted (part (b)).

[{sublist-style}]
. One example is
++\[\begin{align*}
f(x)=\begin{cases}
|x|^{-\frac{1}{2}}-1&|x|\le1\\
0&|x|>1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f1.svg[A function that is integrable but not square-integrable,width=500,role="text-center"]
+
This is because ++\(\int_0^1 x^n\,dx\)++ is finite if and only if ++\(n > -1\)++.
So ++\(x^{-\frac{1}{2}}\)++ is integrable, but its square, ++\(x^{-1}\)++, is not.

. One example is
++\[\begin{align*}
f(x)=\begin{cases}
\frac{1}{|x|}&|x|\ge1\\
1&|x|<1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f2.svg[A function that is square-integrable but not integrable,width=500,role="text-center"]
+
This is because ++\(\int_1^\infty x^n\,dx\)++ is finite if and only if ++\(n<-1\)++.
So ++\(x^{-1}\)++ is not integrable, but its square, ++\(x^{-2}\)++, is.
====

=== Demonstrations

== Observables

=== Questions
* {q-num} Show that if ++\(P=Q^\dagger Q\)++ for some operator ++\(Q\)++, then ++\(\langle f|Pf\rangle\ge 0\)++ for all ++\(f\)++.
+
.Solution
[%collapsible]
====
If ++\(Q\)++ is defined on domain ++\(\mathcal D\)++, then
++\[
\begin{align*}
\langle f|Pf\rangle&=\langle f|Q^\dagger Qf\rangle\\
&=\langle Qf| Qf\rangle\\
&=\int_\mathcal{D} |Qf|^2\,dx
\end{align*}
\]++

Since ++\(|Qf|^2\)++ is nonnegative, so is any integral of it.
====

* {q-num} Show that ++\(Q^{\dagger\dagger}=Q\)++ for any operator ++\(Q\)++. (In other words, show that the adjoint of the adjoint is the original operator.)
+
.Solution
[%collapsible]
====
Simply by the definition of the adjoint and the fact that ++\(\langle g|f\rangle=\langle f|g\rangle^*\)++, we have, for all ++\(f\)++ and ++\(g\)++,
++\[
\begin{align*}
\langle Q^{\dagger\dagger} f|g\rangle&=\langle f|Q^\dagger g\rangle\\
&=\langle Q^\dagger g|f\rangle^*\\
&=\langle g|Qf\rangle^*\\
&=\langle Qf|g\rangle^{**}\\
&=\langle Qf|g\rangle
\end{align*}
\]++

Now, because the inner product is linear,
++\[
\begin{align*}
0&=\langle Q^{\dagger\dagger} f|g\rangle-\langle Qf|g\rangle\\
&=\langle Q^{\dagger\dagger} f-Qf|g\rangle\\
&=\langle (Q^{\dagger\dagger} -Q)f|g\rangle
\end{align*}
\]++

In particular, taking ++\(g=(Q^{\dagger\dagger} -Q)f\)++, we have

++\[
\begin{align*}
0&=\langle (Q^{\dagger\dagger} -Q)f|(Q^{\dagger\dagger} -Q)f\rangle\\
&=|(Q^{\dagger\dagger} -Q)f|^2
\end{align*}
\]++

Hence ++\((Q^{\dagger\dagger} -Q)f=\vec 0\)++ (0⃗ the vector/function, not 0 the number).
Since ++\(f\)++ was arbitrary, ++\(Q^{\dagger\dagger} -Q\)++ must be the zero operator, and so ++\(Q^{\dagger\dagger} =Q\)++.
====

== Eigenfunctions of a Hermitian Operator

=== Questions

* {q-num} find the eigenfunctions and eigenvalues of the position operator ++\(x\)++, defined by ++\(x(f)=xf\)++, and ++\(p\)++, defined by ++\(p(f)=-i\hbar \frac{\partial f}{\partial x}\)++.

* {q-num} Suppose that ++\(f\)++ is an eigenfunction of operators ++\(Q_1\)++ and ++\(Q_2\)++ with eigenvalues ++\(q_1\)++ and ++\(q_2\)++, respectively.
Show that ++\(f\)++ is an eigenfunction of the following operators, and find the corresponding eigenvalues.
+
[{sublist-style}]
. ++\(\alpha Q_1\)++ for ++\(\alpha\in\mathbb C \)++
. ++\(Q_1+Q_2\)++
. ++\(Q_1Q_2\)++
. ++\(Q_2Q_1\)++

+
.Solution
[%collapsible]
====
The following laws are helpful:

* Operator application is associative
* Operator application distributes over addition
* Scalars commute with everything

//

[{sublist-style}]
. ++\(((\alpha Q_1)f=\alpha (Q_1f)=\alpha q_1f\)++, so ++\(f\)++ is an eigenfunction of ++\(\alpha Q_1\)++ with eigenvalue ++\(\alpha q_1\)++.
. ++\((Q_1+Q_2)f=Q_1f+Q_2f=q_1f+q_2f=(q_1+q_2)f\)++, so ++\(f\)++ is an eigenfunction of ++\(Q_1+Q_2\)++ with eigenvalue ++\(q_1+q_2\)++.
. {blank}
++\[
\begin{align*}
(Q_1Q_2)f&=Q_1(Q_2f)\\
&=Q_1(q_2f)\\
&=q_2(Q_1f)\\
&=q_2q_1f
\end{align*}
\]++
So ++\(f\)++ is an eigenfunction of ++\(Q_1Q_2\)++ with eigenvalue ++\(q_1q_2\)++
. The proof proceeds exactly as above. The eigenvalue is again ++\(q_1q_2\)++. So, while operators may not commute, the eigenvalues of the product of two operators does not depend on the order of the product.
====

* {q-num} Find the eigenfunctions and eigenvalues of the operator ++\(\frac{d^n}{dx^n}\)++ for positive integer ++\(n\)++.
(Don't worry about whether the solutions are square-integrable.)
+
.Solution
[%collapsible]
====
For fixed ++\(q\ne 0\)++, solving ++\(\frac{d^n}{dx^n}f(x)=qf(x)\)++ yields
++\[ f_q(x)=\sum_{k=1}^{n}c_k \exp\left[(-1)^{2k/n}q^{1/n}x\right] \]++
where ++\(f_q\)++ is the eigenfunction belonging to eigenvalue ++\(q\)++, and the ++\(c_k\)++ are constants determined by the boundary conditions.
Evidently, every nonzero complex number is an eigenvalue.

If ++\(q=0\)++, then the solutions to ++\(\frac{d^n}{dx^n}f(x)=0\)++ are simply the polynomials of degree at most ++\(n-1\)++.

NOTE: This problem highlights the fact that the eigenfunctions of an operator depend on the _precise_ operator in question; ++\(\frac{d^n}{dx^n}-q\)++ is quite different from ++\(\frac{d^n}{dx^n}\)++ when ++\(q\ne0\)++.
====

== Generalized Statistical Interpretation

== The Uncertainty Principle

== Vectors and Operators

=== Questions

* {q-num} Find the eigenvalues and normalized eigenvectors of
++\[A=\begin{pmatrix}4&2\\1&5\end{pmatrix}\]++
+
.Solution
[%collapsible]
====
We wish to solve ++\(A|x\rangle=\lambda |x\rangle\)++ with ++\(|x\rangle\ne |0\rangle\)++.
Subtracting ++\(\lambda|x\rangle\)++ from both sides and factoring, we obtain ++\((A-\lambda I)|x\rangle=|0\rangle\)++, where ++\(I\)++ is the identity matrix (of the correct dimensions; in this case, ++\(2\times 2\)++).
Since ++\(|x\rangle\ne |0\rangle\)++, ++\(A-\lambda I\)++ must be singular (non-invertible), which means its determinant is 0.
So, we have
++\[\begin{align*}
0&=\det (A-\lambda I)\\&=(4-\lambda)(5-\lambda)-1\cdot 2\\&=\lambda^2-9\lambda+18\\&=(\lambda-3)(\lambda-6)
\end{align*}\]++
So the eigenvalues are ++\(\lambda_1=3\)++ and ++\(\lambda_2=6\)++.

Now we must solve ++\(\lambda_i|x\rangle x=A|x\rangle\)++ for the concrete eigenvalues ++\(\lambda_1, \lambda_2\)++.
If ++\(|x\rangle=\begin{bmatrix}x\\y\end{bmatrix}\)++, then we find the eigenvectors corresponding to ++\(\lambda_1\)++ as follows:
++\[
\begin{align*}
3\begin{bmatrix}x\\y\end{bmatrix}&=\begin{pmatrix}4&2\\1&5\end{pmatrix}\begin{bmatrix}x\\y\end{bmatrix}=\begin{bmatrix}4x+2y\\x+5y\end{bmatrix}
\end{align*}
\]++
Since equal vectors must have equal components, we have the system of equations ++\(3x=4x+2y,3y=x+5y\)++.
This has solution ++\(x=-2y\)++, which means the eigenvectors corresponding to ++\(\lambda_1=3\)++ are of the form ++\(\begin{bmatrix}-2y\\y\end{bmatrix}\)++, which as a unit vector is ++\(\dfrac{1}{\sqrt{5}}\begin{bmatrix}-2\\1\end{bmatrix}\)++.

Similarly, for ++\(\lambda_2=6\)++, we obtain ++\(6x=4x+2y,6y=x+5y\)++ which has solution ++\(x=y\)++, so the unit eigenvector is ++\(\dfrac{1}{\sqrt{2}}\begin{bmatrix}1\\1\end{bmatrix}\)++.
====

* {q-num} What are the eigenvalues and normalized eigenvectors of a diagonal matrix ++\(A\)++ with diagonal entries ++\(m_1, \ldots, m_n\)++?
+
.Solution
[%collapsible]
====
An ++\(n\)++-dimensional matrix can have at most ++\(n\)++ linearly independent eigenvectors, so if we find ++\(n\)++ eigenvectors then we're done.
If we define ++\(v_k:=\)++ the ++\(k\)++^th^ column of the ++\(n\times n\)++ identity matrix — i.e., ++\(v_k\)++ is the vector whose only nonzero component is component ++\(k\)++, which is 1 — then clearly ++\(Av_k=m_k v_k\)++.
So the normalized eigenvalues are these ++\(v_k\)++ and the corresponding eigenvalues are ++\(\lambda_k=m_k\)++.
====

* {q-num} [This problem is technically in Griffiths but I imagine it's also in every linear algebra book ever written.] Suppose ++\(P\)++ is a projection operator, i.e., that it can be written as ++\(P=|a\rangle\langle a|\)++ for some unit vector ++\(a\)++.
+
[{sublist-style}]
. Show that ++\(P\)++ is _idempotent_, i.e., that ++\(P^2=P\)++.
(Corollary: ++\(P^n=P\)++ for every positive integer ++\(n\)++.)
. What are the eigenvalues of ++\(P\)++?
. What are the corresponding eigenvectors? (With ++\(P\)++ arbitrary, can't write out the eigenvectors explicitly, so merely describe them in terms of ++\(a\)++.)

+
.Solution
[%collapsible]
====
[{sublist-style}]
. Every projection operator is of the form ++\(P=|a\rangle\langle a|\)++ where ++\(a\)++ is a unit vector.
So
++\[\begin{align*}
P^2&=(|a\rangle\langle a|)(|a\rangle\langle a|)\\
&=|a\rangle(\langle a|a\rangle)\langle a|\\
&=|a\rangle(1)\langle a|\\
&=|a\rangle\langle a|\\
&=P
\end{align*}\]++

. We wish to solve ++\(P|x\rangle=\lambda|x\rangle\)++ (with ++\(|x\rangle\ne |0\rangle\)++).
By the corollary to part (a), for every positive integer ++\(n\)++, we have ++\(\lambda^{n+1}|x\rangle=P^{n+1}|x\rangle=P|x\rangle=\lambda x\)++, and so ++\((\lambda^{n+1}-\lambda)|x\rangle=|0\rangle\)++.
Since ++\(|x\rangle\ne |0\rangle\)++, we have ++\(\lambda^{n+1}=\lambda\)++.
The only values of ++\(\lambda\)++ for which this holds for all ++\(n\)++ are ++\(\lambda_0=0\)++ and ++\(\lambda_1=1\)++, so those are the two eigenvalues.
. We simply solve for ++\(|x\rangle\)++ corresponding to ++\(\lambda_0\)++:
++\[
|a\rangle\langle a|x\rangle=P|x\rangle=\lambda_0|x\rangle=|0\rangle
\]++
++\(|a\rangle\ne|0\rangle\)++, so ++\(\langle a|x\rangle=0\)++.
Thus the eigenvectors corresponding to ++\(\lambda_0=0\)++ are the vectors orthogonal to ++\(a\)++.
+
Now we solve for ++\(|x\rangle\)++ corresponding to ++\(\lambda_1\)++: ++\[
|a\rangle\langle a|x\rangle=P|x\rangle=\lambda_1|x\rangle=|x\rangle
\]++
Since ++\(\langle a|x\rangle\)++ is just a scalar, the eigenvectors corresponding to ++\(\lambda_1=1\)++ are the vectors parallel to ++\(a\)++.
====

* For an operator ++\(A\)++, the _operator exponential_ is defined by replacing ++\(x\)++ in the power series for ++\(e^x\)++ with ++\(A\)++:
++\[e^{A}:=\sum_{n=0}^\infty \frac{A^n}{n!}.\]++
The operator exponential ++\(e^A\)++ shares some properties with the ordinary exponential ++\(e^x\)++ over complex numbers.
+
[{sublist-style}]
.. Show that ++\(e^A\)++ is always invertible.
.. Show that ++\(e^{A^*}=(e^A)^*\)++.
.. Show that if ++\(A\)++ is hermitian then so is ++\(e^A\)++.
.. Under what conditions on operators ++\(A\)++ and ++\(B\)++ does it hold that ++\(e^{A+B}=e^Ae^B\)++?


* {q-num} Show that the solution to the differential equation ++\(\langle \frac{d}{dt}|x(t)\rangle=\langle A|x(t)\rangle\)++ with initial condition ++\(|x(0)\rangle=|x_0\rangle\)++ is ++\(x=x_0 e^{At}\)++.
+
NOTE: This exactly mirrors the differential equation ++\(\frac{d}{dt}y(t)=ky(t),y(0)=y_0\)++, which has solution ++\(y(t)=y_0 e^{kt}\)++.
