[.qm-chapter.chap-6]
= Chapter 6: Symmetries and Conservation Laws
include::shared_attributes.adoc[]

== Introduction

=== Questions

* {q-num} Given a regular ++\(n\)++-sided polygon ++\(P_n\)++, a symmetry of ++\(P_n\)++ is any mapping ++\(f\)++ from the vertices to the vertices that preserves adjacency: if and only if vertices ++\(v_i\)++ and ++\(v_j\)++ are adjacent in ++\(P_n\)++, then ++\(f(v_i)\)++ and ++\(f(v_j)\)++ are adjacent in ++\(f(P_n)\)++.
.. Explicitly compute the symmetries of the equilateral triangle.
How many are there?
.. Do the same for the square.
.. In words, describe the symmetries of ++\(P_n\)++.

* {q-num} Show that ++\(\hat T(a)\hat\Pi=\hat\Pi\hat T(-a)\)++
+
.Solution
[%collapsible]
====
We simply compute, using the test function ++\(f\)++:
++\[\begin{align*}
\hat T(a)\hat\Pi f(x)&=\hat T(a) f(-x)\\
&=f(-x-a)\\
&=\hat\Pi f(x+a)\\
&=\hat\Pi \hat T(-a)f(x)
\end{align*}\]++
as desired.
====

== The Translation Operator

=== Questions

* {q-num} Show that _all_ observables invariant under translation (observables ++\(Q\)++ for which ++\(\hat T^\dagger QT=Q\)++) are of the form ++\(Q(x,p)=\sum_{n=0}^\infty a_n p^n\)++, where the ++\(a_n\)++ are constants.

== Conservation Laws

== Parity

=== Questions

* {q-num} Show that the position and momentum operators are "`odd under parity`": if ++\(\hat\Pi\)++ is the parity operator, then

+
[{sublist-style}]
.. ++\(\hat\Pi^\dagger \,\hat x\,\hat\Pi=-\hat x\)++
.. ++\(\hat\Pi^\dagger \,\hat p\,\hat\Pi=-\hat p\)++

+
--
You may assume that ++\(\hat \Pi\)++ is hermitian.

.Solution
[%collapsible]
====
.. Using the test function ++\(f\)++, we have
++\[\begin{align*}
\hat\Pi^\dagger \,\hat x\,\hat\Pi f(x)&=\hat\Pi^\dagger \,\hat x f(-x)\\
&=(-\hat x)f(x)
\end{align*}\]++
So indeed ++\(\hat\Pi^\dagger \,\hat x\,\hat\Pi=-\hat x\)++.
.. Similarly,
++\[\begin{align*}
\hat\Pi^\dagger \,\hat p\,\hat\Pi f(x)&=\hat\Pi^\dagger \,\hat p f(-x)\\
&=\hat\Pi^\dagger \left(-ih\frac{d}{dx}\right)f(-x)\\
&=-ih\frac{d}{d(-x)}f(x)\\
&=ih\frac{d}{dx}f(x)\\
&=-\hat pf(x)
\end{align*}\]++
So indeed ++\(\hat\Pi^\dagger \,\hat p\,\hat\Pi=-\hat p\)++.
====
--

* {q-num} Compute the following two operator exponentials in terms of ++\(\hat\Pi\)++, ++\(I\)++ (the identity operator), ++\(\cos\)++, ++\(\sin\)++, ++\(\cosh\)++ (the hyperbolic cosine), and ++\(\sinh\)++ (the hyperbolic sine):
+
[{sublist-style}]
.. ++\(\exp(\hat\Pi)\)++
.. ++\(\exp(i\hat\Pi)\)++

+
.Solution
[%collapsible]
====
As ++\(\hat\Pi\)++ is its own inverse,
++\[\begin{align*}
\hat\Pi^n &=\begin{cases}
\hat\Pi&n\ \textrm{odd}\\
I&n\ \textrm{even}
\end{cases}
\end{align*}\]++

[{sublist-style}]
. Then,
++\[\begin{align*}
\exp(\hat\Pi)&=\sum_{n=0}^\infty \frac{\hat\Pi^n}{n!}\\
&=\sum_{\substack{n=0\\n\ \textrm{even}}}^\infty \frac{\hat\Pi^n}{n!}+\sum_{\substack{n=1\\n\ \textrm{odd}}}^\infty \frac{\hat\Pi^n}{n!}\\
&=\sum_{\substack{n=0\\n\ \textrm{even}}}^\infty \frac{I}{n!}+\sum_{\substack{n=1\\n\ \textrm{odd}}}^\infty \frac{\hat\Pi}{n!}\\
&=I\left(\frac{e+e^{-1}}{2}\right)+\hat\Pi\left(\frac{e-e^{-1}}{2}\right)\\
&=I\cosh(1)+\hat\Pi\sinh(1)
\end{align*}\]++
. Similarly,
++\[\begin{align*}
\exp(i\hat\Pi)&=\sum_{\substack{n=0\\n\ \textrm{even}}}^\infty \frac{(i\hat\Pi)^n}{n!}+\sum_{\substack{n=1\\n\ \textrm{odd}}}^\infty \frac{(i\hat\Pi)^n}{n!}\\
&=\sum_{\substack{n=0\\n\ \textrm{even}}}^\infty \frac{I(-1)^{n/2}}{n!}+\sum_{\substack{n=1\\n\ \textrm{odd}}}^\infty \frac{\hat\Pi(-1)^{n/2}}{n!}\\
&=I\sum_{n=0}^\infty \frac{(-1)^{n}}{(2n)!}+i\hat\Pi\sum_{n=0}^\infty \frac{(-1)^{n}}{(2n+1)!}\\
&=I\cos(1)+\hat\Pi i\sin(1)
\end{align*}\]++
====

== Rotational Symmetry

=== Questions

== Degeneracy

=== Questions
