= Chapter 1: The Wave Function
include::shared_attributes.adoc[]

== The {sch} Equation
=== Questions
* *{q-num}* In the absence of potential (\(V(x,t)=0\)), the {sch} equation can be written as
++\[\frac{\partial\Psi}{\partial t}=\kappa\frac{\partial^2\Psi}{\partial x^2}\]++
with ++\(\kappa=\frac{i\hbar}{2m}\)++.
The physical interpretation of the position wavefunction \(\Psi\) is that its square magnitude is the probability density of a particle's position.
+
Compare this form of the {sch} equation to the https://en.wikipedia.org/wiki/Heat_equation[Heat Equation].
What does this tell you about how the wavefunction flows over time?
+
NOTE: Unlike in the heat equation, \(\kappa\) is imaginary, so the analog is not perfect.
However it is still instructive and at a high level gives good intuition for how probability density "`flows`" over time.
+
.Solution
[%collapsible]
====
Wavefunctions share the following features with solutions to the heat equation:

* Solutions are waves!
* In the heat equation, with ++\(\kappa\)++ real, heat flows opposite the direction of the temperature gradient, and flows with a magnitude proportional to the magnitude of the gradient.
In the {sch} equation, with ++\(\kappa\)++ imaginary, "`probability current`" (which you will learn about later, but for now take it as a given that it is aptly named) flows opposite the direction of the gradient of the wavefunction's phase, and with a magnitude proportional to this gradient's magnitude.

* As with the heat equation, solutions to the {sch} equation in free space get smoother and more diffuse over time.
Combined with the above point, this means that the more concentrated a wavefunction is in space initially, the more rapidly it spreads out.
====

* *{q-num}* [Modified from Townsend] Show that the {sch} is linear: if \(\Psi_{n}\) is a solution to the {sch} equation, then \(\Psi = \sum_{n}c_n \Psi_n\) is also a solution.
+
.Solution
[%collapsible]
====
Ultimately this is just due to the linearity of the differentiation operator and of ordinary multiplication.

If ++\(\Psi_n\)++ is a solution to the {sch} equation then ++\[-i\hbar \frac{\partial \Psi_{n}}{\partial t} - \frac{\hbar ^2}{2m}\frac{\partial ^2 \Psi_n}{\partial x^2}+ V(x)\Psi_n = 0\]++
Now for ++\(\Psi\)++,
++\[\begin{align*}
&\phantom{=}-i\hbar \frac{\partial \Psi}{\partial t} - \frac{\hbar ^2}{2m}\frac{\partial ^2 \Psi}{\partial x^2}+ V(x)\Psi\\
&= -i\hbar \frac{\partial }{\partial t}\sum_n c_n\Psi_n - \frac{\hbar ^2}{2m}\frac{\partial ^2 }{\partial x^2}\sum_n c_n\Psi_n + V(x)\sum_n c_n\Psi_n\\
& = \sum_n -i\hbar \frac{\partial }{\partial t}(c_n\Psi_n) - \sum_n \frac{\hbar ^2}{2m}\frac{\partial ^2 }{\partial x^2} (c_n\Psi_n) + \sum_n V(x) (c_n\Psi_n) \\
&= \sum_n c_n (-i\hbar \frac{\partial \Psi_n }{\partial t} -  \frac{\hbar ^2}{2m}\frac{\partial ^2 \Psi_n}{\partial x^2} +  V(x) \Psi_n )\\
&=\sum_n c_n \cdot 0= 0 \end{align*}\]++
We find that if ++\(\Psi_n\)++ is a solution to the {sch}, then ++\(\Psi = \sum_n c_n \Psi_n\)++ is also a solution to the {sch} equation.
====

* *{q-num}* [Modified from Townsend] Show that ++\(u(x,t) = A\cos(\omega t+ \phi) \sin(\frac{n\pi x}{l}) \)++ (with appropriate choices of  ++\(\omega,n,l\)++) is a solution to the classical wave equation, ++\( \frac{1}{v^2}\frac{\partial ^2 u}{\partial t^2} = \frac{\partial ^2 u }{\partial x^2}\)++, but *not* the {sch} equation.
(Ignore the trivial case where \(u=0\).)
+
.Solution
[%collapsible]
====
For \(u(x,t)\) to be a solution to the classical wave equation, ++\( \frac{1}{v^2}\frac{\partial ^2 u}{\partial t^2} - \frac{\partial ^2 u }{\partial x^2} = 0\)++.
For ++\(u(x,t)\)++ to be a solution to the {sch} equation for a free particle then ++\(-i\hbar \frac{\partial u}{\partial t} - \frac{\hbar ^2}{2m}\frac{\partial ^2 u}{\partial x^2} = 0\)++.
Let's begin with the classical wave equation:
++\[\begin{align*}
\frac{1}{v^2}\frac{\partial ^2 u}{\partial t^2} - \frac{\partial ^2 u }{\partial x^2}
&= \frac{1}{v^2}\frac{\partial ^2}{\partial t^2}\left[A\cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)\right] - \frac{\partial ^2}{\partial x^2} \left[A\cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)\right] \\
&=-A\frac{\omega^2}{v^2}\cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right) + A\left(\frac{n\pi}{l}\right)^2 \cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)\\
&=\left[\left(\frac{n\pi}{l}\right)^2-\frac{\omega^2}{v^2}\right]A\cos(\omega t+\phi)\sin\left(\frac{n\pi x}{l}\right)
\end{align*}
\]++
We see that if ++\(v = \frac{\omega l}{n \pi}\)++ then \(u(x,t)\) is a solution to the classical wave equation. For the {sch} equation,
++\[\begin{align*}
&\phantom{=}-i\hbar \frac{\partial u}{\partial t} - \frac{\hbar ^2}{2m}\frac{\partial ^2 u}{\partial x^2} \\
&= [-i\hbar \frac{\partial}{\partial t}\left[A\cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)\right]
    - \frac{\hbar ^2}{2m}\frac{\partial ^2}{\partial x^2}\left[A\cos(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)\right] \\
&= Ai\hbar\omega\sin(\omega t+ \phi) \sin\left(\frac{n\pi x}{l}\right)+A\frac{\hbar ^2}{2m}\left(\frac{n \pi}{l}\right)^2\cos(\omega t+ \phi)\sin\left(\frac{n\pi x}{l}\right)
\end{align*}\]++
In order for this to equal 0 for all ++\(x,t\)++, and for \(u\) to be nontrivial, we must have
++\[i\hbar\omega\sin(\omega t+ \phi) +\frac{\hbar ^2}{2m}\left(\frac{n \pi}{l}\right)^2\cos(\omega t+ \phi) = 0\]++
There are no conditions we can impose on the constants \(\omega, n, l, \phi\) so that this is true for all time, so ++\(u(x,t) = A\cos(\omega t+ \phi) \sin(\frac{n\pi x}{l}) \)++ is not a solution to the {sch} equation for a free particle.

====

=== Demonstrations
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/collapse_of_wavefunction_direction_and_momentum/collapse_of_wavefunction_direction_and_momentum_inlined.html[Collapse of Wavefunction Direction and Momentum]
** Notes: for this section, show just the position component; remove momentum.

=== Other Ideas, Notes, Materials

* Interactive timeline like the ones in some of our WSU courses (e.g., https://worldscienceu.com/lessons/1-4-from-einstein-to-ligo/[From Einstein to Ligo^]).


== The Statistical Interpretation

=== Questions
* *{q-num}* In which of the following variations of the double slit experiment will a wavelike interference pattern be observed?

** Using single photons
** Using single electrons
** Using a beam of electrons
** Measuring which slit the particle passes through
** Using helium atoms

+
.Solution
[%collapsible]
====
For the double slit experiment, all light and matter create a wavelike interference pattern, regardless of whether single particles are used or beams of particles are used.
In quantum mechanics, wavelike interference is not an artifact of collective motion -- a single particle passes through both slits and interacts with _itself_!
We see a wavelike interference pattern for a single photon, a single electron, a beam of electrons, or even helium atoms!
However, if we set up an apparatus to measure which slit the particles travel through, we do _not_ observe an interference pattern because the wavefunctions collapse upon measurement.
====

* *{q-num}* Let's derive some of the observed properties of the interference pattern in the double slit experiment. Suppose that the (monochromatic) light has a wavelength \(\lambda\), that the slits are a distance \(d\) apart, and that the detector screen is a distance \(D\gg d\) from the slits.
.. Show that at a point \(P\) an angle \(\theta\) from the center of the detector screen, the difference in path lengths between the slits' two respective waves is given by ++\(\Delta l=d\sin\theta\)++.
.. Show that the locations of maximum constructive interference (maximum intensity) are given by ++\(d\sin\theta=n\lambda\)++ for ++\(n\in\mathbb Z\)++.
.. Show that the locations of maximum destructive interference (minimum intensity) are given by ++\(d\sin\theta=\left(n+\frac{1}{2}\right)\lambda\)++ for ++\(n\in\mathbb Z\)++.
.. Using the assumption that \(D\gg d\) (and so the rays emanating from the two slits are approximately parallel), show that the distance from the center of the detector screen to the \(n\)^th^ crest is approximately \(\frac{n\lambda D}{d}\).

+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====


=== Demonstrations
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/wave_particle_duality_double_slit/wave_particle_duality_double_slit_inlined.html?t=1653613543[Double slit detector simulation (2D)^]
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/constructive_destructive_interference/constructive_destructive_interference_inlined.html?t=1657044227[Double slit with waves (3D)^]

== Probability

* *{q-num}* An integer is chosen uniformly at random from the set ++\(\{0,1, 2,\ldots, 199\}\)++.
+
[{sublist-style}]
.. What are the probabilities of selecting a number with 1, 2, or 3 digits?
.. Calculate the expected number of digits.
.. Find the standard deviation of the number of digits.

+
.Solution
[%collapsible]
====

[{sublist-style}]
. There are 10 possible 1-digit numbers, 90 possible 2-digit numbers, and 100 3-digit numbers.
The probability of selecting a 1, 2, or 3 digit number are: ++\[P(\textrm{1}) = \frac{10}{200} = \frac{1}{20}\]++  ++\[P(\textrm{2}) = \frac{90}{200} = \frac{9}{20}\]++ ++\[P(\textrm{3}) = \frac{100}{200} = \frac{1}{2}\]++
. The expected number of digits is ++\[\begin{align*}\langle d \rangle &= (1)P(1)+(2)P(2) + (3)P(3) \\ &=  (1)\frac{1}{20}+ (2)\frac{9}{20}+(3)\frac{1}{2} \\ &=  2.45  \end{align*}\]++
If you choose a number at random, the expected value for the number of digits is 2.45.
. Standard deviation is given by \(\sqrt{\langle d^2\rangle - \langle d \rangle^2}\), where \(d\) is the number of digits that a selected number has. ++\[\begin{align*} \langle d^2 \rangle  =&  (1^2)P(1)+(2^2)P(2) + (3^2)P(3) \\ =&  (1)\frac{1}{20}+ (4)\frac{9}{20}+(9)\frac{1}{2} \\ =&  6.35 \end{align*}\]++
The standard deviation is: ++\[\sigma = \sqrt{6.35-(2.45)^2} = 0.59\]++
====

* *{q-num}* You survey your neighbors to determine the number of pets they have in their households and collect the following data:
+
--
[#pets-table,cols=">1h,<1",stripes=none,frame=all,grid=rows,width=40em]
|===
|Number of pets in household
s|Number of households with that number of pets
|0|3
|1|6
|2|5
|3|2
|4|2
|5|0
|6|0
|7|1
|8|0
|9|0
|10|1
|===


Verify that both ways of computing standard deviation give the same answer (i.e. show that ++\(\sqrt{\langle (\Delta n)^2 \rangle} = \sqrt{\langle n^2 \rangle - \langle n \rangle ^2}\)++ where n is the number of pets in the household).


.Solution
[%collapsible]
====
Calculate \(\langle n \rangle\), \(\langle n^2 \rangle\), and \(\langle (\Delta n)^2 \rangle\)
++\[\begin{align*} \langle n \rangle =& 0(.15) + 1(.3) + 2 (.25)+ 3(.1)+ 4(.1) + \\ &5(0) + 6(0) + 7(.05) + 8(0) + 9(0) + 10(.05) \\=& 0+ .3 + .5 + .3 + . 4 + 0 + 0+ .35+ 0 + 0 +.5 \\=& 2.35 \end{align*}\]++ ++\[\begin{align*} \langle n^2 \rangle =& 0(.15) + 1(.3) + 4(.25)+ 9(.1)+ 16(.1) + \\ &25(0) + 36(0) + 49(.05) + 64(0) + 81(0) + 100(.05) \\=& 0+ .3 + 1 + .9 + 1.6  + 0 + 0+ 2.45 + 0 + 0 + 5 \\=&  11.25 \end{align*}\]++
++\[\begin{align*} \langle (\Delta n)^2) \rangle =& (0-2.35)^2(.15) + (1-2.35)^2(.3) +(2-2.35)^2(.25) +\\ &(3-2.35)^2(.1)+ (4-2.35)^2(.1) + (5-2.35)^2(0) +\\ &(6-2.35)^2(0) + (7-2.35)^2(.05) + (8-2.35)^2(0) +\\ &(9-2.35)^2(0) + (10-2.35)^2(.05) \\=& 0.828375 + 0.54675 + 0.030625 + 0.04225 + \\ & 0.27225 + 0 + 0 + 1.081125 + 0 + 0 + 2.926125\\ =& 5.7275 \end{align*}\]++
We find that ++\(\sqrt{\langle (\Delta n)^2 \rangle} = \sqrt{\langle n^2 \rangle - \langle n \rangle ^2} = 2.39\)++
====
--

* *{q-num}* Plot the following two probability density distributions over the interval 0 to 1:
+
--
++\[\begin{align*}
\rho_1(x)&=
    \begin{cases}
        4x & 0\le x \le \frac{1}{2}\\
        -4x+4 & \frac{1}{2}\le x\le 1
    \end{cases}\\
    \rho_2(x) &= 2\sin^2(2\pi x)\end{align*}\]++

[{sublist-style}]
. Make a prediction: on your graphs, sketch a solid line where you think the expectation value of x will be and sketch dotted lines where you think the standard deviation will fall.
. Calculate ++\(\langle x \rangle\)++ and ++\(\sigma\)++ for both distributions.
. For both distributions, calculate the probability of selecting a value that falls within 1 standard deviation of the mean.

.Solution
[%collapsible]
====
[{sublist-style}]
. MAKE GRAPHS
. For the first probability distribution, ++\(\rho_1(x)\)++:
++\[\begin{align*} \langle x \rangle =& \int_0^\frac{1}{2} x (4x) dx + \int_\frac{1}{2}^1 x (-4x+4)dx \\
=& \left.\frac{4}{3}x^3 \right|_0^\frac{1}{2} + \left. \left( -\frac{4}{3}x^3 + 2x^2 \right)\right|_\frac{1}{2}^1 \\
=& \frac{1}{6} - \frac{4}{3} + 2 + \frac{1}{6} - \frac{1}{2} = \frac{1}{2} \\
  \langle x^2 \rangle =&   \int_0^\frac{1}{2} x^2 (4x) dx + \int_\frac{1}{2}^1 x^2 (-4x+4)dx \\
=& \left. x^4 \right|_0^\frac{1}{2}  + \left. \left( -x^4 + \frac{4}{3}x^3 \right) \right|_\frac{1}{2}^1 \\
=& \frac{1}{16} - 1 + \frac{4}{3} + \frac{1}{16} - \frac{1}{6} = \frac{7}{24} \\
\sigma =& \sqrt{\langle x^2\rangle - \langle x \rangle^2} = \sqrt{\frac{7}{24}-\frac{1}{4}} \approx 0.204
\end{align*}\]++

For the second probability distribution, ++\(\rho_2(x)\)++:
++\[\begin{align*} \langle x \rangle =& \int_0^1 x (2\sin^2{(2 \pi x)}) dx = \int_0^1 x (1-\cos(4 \pi x)) dx \\
=& \left. \frac{x^2}{2} - \frac{x\sin(4 \pi x)}{4\pi} - \frac{\cos(4 \pi x)}{16\pi^2} \right|_0^1  \\
=& \frac{1}{2} - \frac{1}{16\pi^2} + \frac{1}{16\pi^2} = \frac{1}{2} \\ \langle x^2 \rangle =& \int_0^1 x^2(2\sin^2{(2 \pi x)}) dx = \int_0^1 x^2 (1-\cos(4 \pi x)) dx \\
 =& \left. \frac{x^3}{3} - \frac{x^2\sin(4 \pi x)}{4\pi} - \frac{x\cos(4 \pi x)}{8\pi^2} + \frac{\sin(4 \pi x )}{32 \pi^3}\right|_0^1  \\ =& \frac{1}{3} - \frac{1}{8\pi^2}
 \\  \sigma =& \sqrt{\langle x^2\rangle - \langle x \rangle^2} = \sqrt{\frac{1}{3}-\frac{1}{8\pi^2} - \frac{1}{4}} = \sqrt{\frac{1}{12}-\frac{1}{8\pi^2}} \\
  \approx& 0.266\end{align*}\]++
. For ++\(\rho_1\)++ the probability of selecting a value within one standard deviation of the mean is given by:
++\[\begin{align*} &\int_{0.296}^{0.5} (4x)dx + \int_{0.5}^{0.704} (-4x+4)dx \\ = & \left. 2x^2 \right|_{0.296}^{0.5} + \left. \left( -2x^2 + 4x \right) \right|_{0.5}^{0.704} = 0.650 \end{align*}\]++  For ++\(\rho_2\)++ the probability of selecting a value within one standard deviation of the mean is given by: ++\[\begin{align*} &\int_{0.234}^{0.766} 2\sin^2(2\pi x)dx =  \left. x - \frac{\sin(4 \pi x)}{4 \pi} \right|_{0.234}^{0.766}  = 0.564 \end{align*}\]++
====
--

* *{q-num}* You are standing at the center of a number line (++\(x=0\)++).
You repeatedly flip a coin. Every time you flip heads, you take a unit step in the positive direction.
Every time you flip tails, you take a unit step in the negative direction.
[{sublist-style}]
. Where on the number line could you end up after flipping the coin exactly once (++\(n=1\)++)?
How many total paths are there?
. For ++\(n=0\)++ to ++\(n=3\)++, how many sequences of ++\(n\)++ coin flips land you at each integer?
How many total paths are there?
Do you notice a pattern?
. Use https://en.wikipedia.org/wiki/Pascal's_triangle[Pascal's triangle] to determine the probability of landing at each integer after 7 steps.
Where are you most likely to land?
Calculate the expected value and standard deviation.

+
.Solution
[%collapsible]
====
[{sublist-style}]
. You could end up at ++\(x = \pm 1\)++. There is 1 path, {T}, to ++\(x = - 1\)++ and 1 path, {H}, to ++\(x = - 1\)++, for a total of 2 paths.
. For 0 to 3 flips: +
[underline]#n=0# +
x=0, 1 path: \{X\} +
total: 1 +
[underline]#n=1# +
x=-1, 1 path: \{T\} | x=1, 1 path: \{H\} +
total paths: 2 +
[underline]#n=2# +
x=-2, 1 path: \{TT\} | x=0, 2 paths: \{TH, HT\} | x=2, 1 path: \{HH\} +
total paths: 4 +
[underline]#n=3# +
x=-3, 1 path: \{TTT\} | x=-1, 3 paths: \{TTH, THT, HTT\} | x=1, 3 paths: \{HHT, HTH, THH\} |x=3, 1 path: \{HHH\} +
total paths: 8 +
For each n, there are ++\(2^n\)++ total paths, and the number of paths to get to each endpoint are given by binomial coefficients, which we see in Pascal's triangle.
. [Insert triangle here] Using Pascal's triangle, we come up with the following probabilities:
====


=== Demonstrations

* Discrete density function
** https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/ball_sampling/ball_sampling_inlined.html?t=1656456918[Balls in a bag^]
** https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/dice_sampling/dice_sampling_inlined.html?t=1656456918[Sum of N dice^]
* Continuous density function
** https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/wavefunctions_and_probability_sampling_experiment/wavefunctions_and_probability_sampling_experiment_inlined.html?t=1653613543[Probability and Sampling Experiment (1D)^]
** https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/wavefunctions_and_probability_sampling_experiment_2D/wavefunctions_and_probability_sampling_experiment_2D_inlined.html?t=1653613543[Probability and Sampling Experiment (2D)^]

* Show how the moments of various distributions depend on their parameters (e.g., show one standard deviation of a gaussian and how it changes with the parameter ++\(\sigma\)++).

=== Other Ideas, Notes, Materials

* Discuss basic properties of probability distributions:
** Linearity of expectation
** How scaling ++\(x\)++ affects ++\(\sigma\)++


== Normalization

=== Questions
* *{q-num}* Normalize the following wavefunctions (i.e. find A):
+
[{sublist-style}]
. ++\(\Psi(x,t)= Ae^{-(\frac{ax^2}{2}+i\omega t)}\)++
. ++\(\Psi(x,0)= Ae^{-\kappa|x|}\)++
. ++\(\Psi(x,0)= A\frac{\sin(x)}{x}\)++
. ++\(\Psi(x,t)= A\frac{e^{-i\omega t}}{x+e^{i \pi/2}}\)++

+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====

* *{q-num}* Write a normalized wavefunction, ++\(\Psi(x,t)\)++,  with the following values at time ++\(t=0\)++ :
+
++\[\begin{align*}\langle x \rangle &= 3 \\\sigma &= 2\end{align*}\]++
+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====

* *{q-num}* The probability current describes the rate at which probability flows past point ++\(x\)++. It is given by ++\[J(x,t) = \frac{i
    \hbar}{2m}\left(\Psi\frac{\partial\Psi^{*}}{\partial x}-\Psi^{*}\frac{\partial\Psi}{\partial x}\right)\]++
+
--
[{sublist-style}]
. Show that ++\[\ \frac{d}{dt} \int_a^b |\Psi(x,t)|^2 = J(a,t) - J(b,t) \]++ What happens to the probability current in the region from ++\(-\infty\)++ to ++\(\infty\)++? What does this mean?
. Use https://en.wikipedia.org/wiki/Divergence_theorem[Gauss's Theorem] to extend this result to an arbitrary region ++\(S\)++ in ++\(\mathbb R^n\)++.
. [From the Bernd Thaller book] Write ++\(\Psi(x,t)=|\Psi(x,t)|e^{i\varphi(x,t)}\)++.
Show that ++\(J\)++ as defined above points in the direction of ++\(\nabla \varphi\)++, i.e., in the direction of increasing phase.

.Solution (placeholder)
[%collapsible]
====
This is the solution
====
--

=== Demonstrations

* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/wavefunctions_and_probability_sampling_experiment/wavefunctions_and_probability_sampling_experiment_inlined.html?t=1653613543[Probability and Sampling Experiment (1D)^]
** Already shown above, but this time you can emphasize how after changing the shape of the wavefunction, it immediately adjusts ++\(\psi\)++ so that its (squared) magnitude remains 1.

== Momentum

=== Questions
* *{q-num}* For the following wavefunction ++\[\Psi(x,t) = e^{-i \lambda_1 t}\sin(\pi x) + e^{-i \lambda_2 t}\sin(2 \pi x) \]++
[{sublist-style}]
. Show that ++\(\Psi(x,t)\)++ is normalized.
. Calculate ++\(\langle x \rangle\)++ and ++\(\langle p \rangle \)++
. Calculate ++\(\frac{d \langle x \rangle}{dt}\)++. Does Ehrenfest's theorem hold?
. Find ++\(\langle - \frac{\partial V}{\partial x}\rangle \)++.

+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====


* *{q-num}* Show that in a quadratic potential ++\(V(x)=ax^2+bx+c\)++, the following holds:
++\[\frac{d\langle p \rangle}{dt}=-\left.\frac{\partial V}{\partial x}\right|_{x=\langle x\rangle}\]++
In other words, if the potential is quadratic then we can say "`the expectation of the force at ++\(x\)++ is the force evaluated at ++\(\langle x\rangle\)++`".
+

.Solution
[%collapsible]
====
Starting with Ehrenfest's theorem, all we need to do is compute ++\(-\frac{\partial V}{\partial x}\)++ and use the linearity of expectation:

++\[
\begin{align*}
\frac{d\langle p\rangle}{dt}&=\left\langle-\frac{\partial V}{\partial x}\right\rangle\\
&=\left\langle-(2ax+b)\right\rangle\\
&=-(2a\langle x\rangle + b)\\
&=-\left.\frac{\partial V}{\partial x}\right|_{x=\langle x\rangle}
\end{align*}
\]++

If \(V\) had any higher order \(x\) terms, then its derivative would have a term of order ++\(x^2\)++ or higher, and the above procedure wouldn't work because in general ++\(\langle x^n\rangle\ne\langle x\rangle^n\)++.
====

* *{q-num}* Any dynamical variable can be expressed in terms of position and momentum.
Angular momentum is given by ++\[\textbf{L} = \textbf{r} \times \textbf{p}.\]++
In this problem you will get a small preview of orbital angular momentum, which you will learn much more about in Module 4.
We will be working in three dimensions, where ++\(\textbf{r} = r\hat{r}\)++ and ++\(\textbf{p} = -i \hbar \nabla \)++.
+
--
[{sublist-style}]
. Find the expression for ++\(\textbf{L}\)++ in spherical coordinates.
. Find ++\(L^2\)++.
. Calculate ++\(\langle L^2 \rangle\)++ for the spatial component of the wavefunction ++\( \sqrt{\frac{15}{8\pi}}\sin{\theta}\cos{\theta}e^{-i\phi} \)++

.Solution (placeholder)
[%collapsible]
====
This is the solution
====
--

=== Demonstrations
* Demonstrate Ehrenfest's Theorem on various wavefunctions evolving over time by showing ++\(\langle x\rangle_\psi\)++ and ++\(\langle p\rangle_\psi\)++.
** [x] Harmonic oscillator: https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/harmonic_oscillator/harmonic_oscillator_evolution_inlined.html?t=1653613543[the quantum harmonic oscillator^]
** [ ] Particle in a box
** [ ] others?
* Sample from these wavefunctions, e.g., let the harmonic oscillator evolve a bunch, then sample its position at a given point in time (pretending that we have an ensemble of identically prepared harmonic oscillators).
Let the resulting ++\(\delta\)++ function evolve (spread out, oscillate), then sample again. Etc.
** Unfortunately this doesn't seem feasible.
The universe is fortunate to get to run its computations instantly, but computers aren't so lucky.
While in QM a wavefunction is an infinite linear combination of basis functions, actually rendering it on a computer requires taking only a finite linear combination, and for Gaussians with variance outside a relative narrow band centered around 1 it takes more terms to render them faithfully than be computed in a reasonable amount of time.


== The Uncertainty Principle

=== Questions
* *{q-num}* For the wavefunction from question {q-num}, ++\[\Psi(x,t) = e^{-i \lambda_1 t}\sin(\pi x) + e^{-i \lambda_2 t}\sin(2 \pi x) \]++
[{sublist-style}]
. Calculate ++\(\langle p^2\rangle\)++ and ++\(\sigma_p\)++.
. What is the minimum possible value of ++\(\sigma_x\)++?
. Calculate ++\(\langle x^2 \rangle\)++ and ++\(\sigma_x\)++. Does the Heisenberg uncertainty principle hold?

+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====


* *{q-num}* Estimate ++\(\sigma_p\)++ for a photon that is confined to a cone cell in the eye with a diameter of 2 ++\(\mu\)++m.
+
.Solution (placeholder)
[%collapsible]
====
This is the solution
====



=== Demonstrations
* https://dts333.github.io/WSF-Demos/RB/src/dist/Quantum%20Mechanics/New%20demos/fourier_transform_gaussian/fourier_transform_gaussian_inlined.html?t=1653613543[Fourier Transformed Gaussian^]


// Verify Ehrenfest's theorem for the following wavefunction:

//[stem]
//++++
//\Psi(x,t) = \left(\frac{a}{\pi}\right)^{\frac{1}{4}}e^{-(\frac{a x^2}{2}+i\omega t) }
//++++

//where

//[stem]
//++++
//a=\frac{m\omega}{\hbar}
//++++

// . Calculate ++\(\frac{d\langle p \rangle}{dt}\)++
// . Use Schrodinger's equation to find ++\(V(x)\)++.
// . Calculate ++\(\left\langle -\frac{\partial V}{\partial x} \right\rangle\)++. Does Ehrenfest's theorem hold?
// . This wavefunction is the ground state of the quantum harmonic oscillator, the quantum analog of a https://en.wikipedia.org/wiki/Harmonic_oscillator[classical spring^] that has been displaced from its equilibrium.
//What does part (c) tell you about the behavior of the quantum harmonic oscillator?
//How does this compare to the classical harmonic oscillator?

// end::content[]
