= Chapter 3: Formalism
include::shared_attributes.adoc[]

== Hilbert Space

=== Questions

* *3.1.{counter:qn}*
A function ++\(f\)++ is said to absolutely integrable when ++\(|f|\)++ is integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is absolutely integrable, but not square-integrable.
.. Find a continuous function ++\(f:\mathbb R\to\mathbb R\)++ that is square-integrable, but not absolutely integrable.

+
.Solution
[%collapsible]
====
The "`trick`" is find functions that approach the x- or y-axis quickly enough to have a finite integral, but no longer do so when squared (part (a)) or square-rooted (part (b)).

[{sublist-style}]
* One example is
++\[\begin{align*}
f(x)=\begin{cases}
|x|^{-\frac{1}{2}}-1&|x|\le1\\
0&|x|>1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f1.svg[A function that is integrable but not square-integrable,width=500,role="text-center"]
+
This is because ++\(\int_0^1 x^n\,dx\)++ is finite if and only if ++\(n > -1\)++.
So ++\(x^{-\frac{1}{2}}\)++ is integrable, but its square, ++\(x^{-1}\)++, is not.

* One example is
++\[\begin{align*}
f(x)=\begin{cases}
\frac{1}{|x|}&|x|\ge1\\
1&|x|<1
\end{cases}
\end{align*}
\]++
+
image::fig-3.1.1-f2.svg[A function that is square-integrable but not integrable,width=500,role="text-center"]
+
This is because ++\(\int_1^\infty x^n\,dx\)++ is finite if and only if ++\(n>1\)++.
So ++\(x^{-1}\)++ is not integrable, but its square, ++\(x^{-2}\)++, is.
====

=== Demonstrations

:!qn:
== Observables

* *3.2.{counter:qn}* Show that if ++\(P=Q^\dagger Q\)++ for some operator ++\(Q\)++, then ++\(\langle f|Pf\rangle\ge 0\)++ for all ++\(f\)++.
+
.Solution
[%collapsible]
====
If ++\(Q\)++ is defined on domain ++\(\mathcal D\)++, then
++\[
\begin{align*}
\langle f|Pf\rangle&=\langle f|Q^\dagger Qf\rangle\\
&=\langle Qf| Qf\rangle\\
&=\int_\mathcal{D} |Qf|^2\,dx
\end{align*}
\]++

Since ++\(|Qf|^2\)++ is nonnegative, so is any integral of it.
====


* *3.2.{counter:qn}* Show that ++\((Q^\dagger)^\dagger=Q\)++ for any operator ++\(Q\)++.
+
.Solution
[%collapsible]
====
Simply by the definition of the adjoint and the fact that ++\(\langle g|f\rangle=\langle f|g\rangle^*\)++, we have, for all ++\(f\)++ and ++\(g\)++,
++\[
\begin{align*}
\langle (Q^\dagger)^\dagger f|g\rangle&=\langle f|Q^\dagger g\rangle\\
&=\langle Q^\dagger g|f\rangle^*\\
&=\langle g|Qf\rangle^*\\
&=\langle Qf|g\rangle^{**}\\
&=\langle Qf|g\rangle
\end{align*}
\]++

Now, because the inner product is linear,
++\[
\begin{align*}
0&=\langle (Q^\dagger)^\dagger f|g\rangle-\langle Qf|g\rangle\\
&=\langle (Q^\dagger)^\dagger f-Qf|g\rangle\\
&=\langle ((Q^\dagger)^\dagger -Q)f|g\rangle
\end{align*}
\]++

In particular, taking ++\(g=((Q^\dagger)^\dagger -Q)f\)++, we have

++\[
\begin{align*}
0&=\langle ((Q^\dagger)^\dagger -Q)f|((Q^\dagger)^\dagger -Q)f\rangle\\
&=|((Q^\dagger)^\dagger -Q)f|^2
\end{align*}
\]++

Hence ++\(((Q^\dagger)^\dagger -Q)f=0\)++.
Since ++\(f\)++ was arbitrary, ++\((Q^\dagger)^\dagger -Q\)++ must be the zero operator, and so ++\((Q^\dagger)^\dagger =Q\)++.
====
