[.qm-chapter.chap-5]
= Chapter 5: Identical Particles
include::shared_attributes.adoc[]

== Two-Particle Systems

=== Questions

* {q-num} Show that an operator ++\(P\)++ satisfying ++\(P^2=I\)++ (such as the *exchange operator*) has no eigenvalues other than ++\(1\)++ and ++\(-1\)++.
(Since the eigenvalues are real, such an operator is necessarily hermitian.)
+
.Solution
[%collapsible%open]
====
We want to solve ++\(Pf=\lambda f\)++ with ++\(f\ne\ket0\)++.
Multiplying both sides by ++\(P\)++, we have
++\[\begin{align*}
f&=P^2f\\
&=P(Pf)\\
&=P(\lambda f)\\
&=\lambda (Pf)\\
&=\lambda^2 f
\end{align*}\]++
Since ++\(\lambda^2 f=f\)++ and ++\(f\ne\ket0\)++, we see that ++\(\lambda^2=1\)++.
The only solutions to this equation are ++\(\lambda=\pm 1\)++.
(++\(P\)++ need not have _both_ ++\(+1\)++ and ++\(-1\)++ as eigenvalues; the identity operator itself satisfies ++\(P^2=I\)++ but its only eigenvalue is ++\(1\)++.
++\(\pm1\)++ are simply the only _permissible_ eigenvalues.)
====

* {q-num} Suppose three fermions labeled ++\((1,2,3)\)++ are exchanged so that they are now labeled ++\((3,1,2)\)++.
In terms of the original wavefunction, what is the new wavefunction? UPDATE THIS ONE AS DISCUSSED
+
.Solution
[%collapsible]
====
The three-way swap can be decomposed into pairwise swaps: first we swap 1 and 2 to obtain ++\((2,1,3)\)++, and then we swap 2 and 3 to obtain ++\((3,1,2)\)++.
Since both two-particle swaps multiply the wavefunction by ++\(-1\)++ (because the particles are fermions), the net result is that resulting wavefunction is equal to the original wavefunction.
====

* {q-num} Show that ... write out first few states for e4

* {q-num} Show that ... full wavefunction (sping and spatial) for indistinguisahble boson, fermion, and distinguishable particles

* {q-num} Show that ... central potential question

== Atoms

== Solids

== Demonstrations
